# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:17.4@sha256:617b2ef2238fa48069b763200b88d5a04f52f4eefedbda90716a37bf8a8b8066

  postgresql:
    shared_preload_libraries:
      - "vectors.so"

  storage:
    size: 8Gi
    storageClass: local-hostpath
  
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";

  backup:
    barmanObjectStore:
      destinationPath: "s3://potatobread-homelab-backup/cnpg/immich"
      endpointURL: s3.us-west-000.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-paperless-backup
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-paperless-backup
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: bzip2
      data:
        compression: bzip2