apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  instances: 3

  storage:
    size: 8Gi
    storageClass: local-hostpath
  
  bootstrap:
    initdb:
      database: immich
      owner: immich

  backup:
    barmanObjectStore:
      destinationPath: "s3://potatobread-homelab-backup/cnpg/immich"
      endpointURL: s3.us-west-000.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-paperless-backup
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-paperless-backup
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: bzip2
      data:
        compression: bzip2