apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api
type: Opaque
stringData:
    api_token: ENC[AES256_GCM,data:zyhKSbLMEYidoJOl5kQ1Gbq58QfPWx78g8kpmFkfJgSGZBf/g1/zmg==,iv:CRcQ0cRxDgGYqKayK9IF+9ynbwBdSQqLKglwM4ESGvU=,tag:4ML5+FyHS/phbCtjPjW0FQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdHBDQU1UQnZMMGtSWDQw
            QVhPalMveEdvc1NZOFZONzJzRDZTbnhBVUNZCldia1ZhUjJDS2F4SHpZRFhDWnUy
            MEFhdnhOV01pUWtCSU9TNTNXYi93RzAKLS0tIFdhYkdmNVg1YXFadTQ5UUdXTGRa
            V3B0c1lpT2pKdDFSUjBUV0FkZlV2elEK5O/+Q3UU2Vy8VTT1MwRQCZd8nRcXxh1f
            5FKfd6VhHbNTSZe1JlztrzD1VKAbJ66L8RAEr1DLk/hdbFBbjtl89A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T04:02:51Z"
    mac: ENC[AES256_GCM,data:0GTCx0YT6vlFFbgFO8hSqH7Nx969yMLSNh+fcBFJ+2PD2cKxtnMYyxIhazLZyjV8+IOQSsbH07uiK5wUNVBwd4km55PcyYr4qNab3QOzVLuiZIxHQ0TRo3zIgIrmeM3PghyXZ8qDIK3b5Onz3nqdO/6H5HwAYjlv9VZFbVsCARE=,iv:Kox2TlEXhfornAqMh1hKBNGeaOL4pcEiL7ixHuCzvlo=,tag:sgDF3o0tllg5wnT0p6Cwig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
