apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-certs
spec:
  secretName: homelab-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "potatobread.dev"
    - "*.potatobread.dev"
    - "cornwater.net"
    - "*.cornwater.net"
