apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: potatobread-dev
spec:
  secretName: potatobread-dev-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "potatobread.dev"
    - "*.potatobread.dev"
