---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kritika-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kritika-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        GITHUB_APP_CLIENT_ID: '{{ index . "GITHUB_APP_CLIENT_ID" }}'
        GITHUB_APP_PRIVATE_KEY: '{{ index . "GITHUB_APP_PRIVATE_KEY" }}'
        GITHUB_APP_WEBHOOK_SECRET: '{{ index . "GITHUB_APP_WEBHOOK_SECRET" }}'
  dataFrom:
    - extract:
        key: k8s-kritika-kritika-secret
