apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: paperless-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paperless-app
    spec:
      containers:
        - name: paperless-app
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          resources:
            limits:
              memory: "4Gi"
              cpu: "4"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: paperless-app-vol
              mountPath: /usr/src/paperless/data
              subPath: data
            - name: paperless-app-vol
              mountPath: /usr/src/paperless/media
              subPath: media
            - name: paperless-app-vol
              mountPath: /usr/src/paperless/export
              subPath: export
            - name: paperless-ingest-vol
              mountPath: /usr/src/paperless/consume
              subPath: consume
          envFrom:
            - configMapRef:
                name: paperless-app-config
            - secretRef:
                name: paperless-postgres-secrets
            - secretRef:
                name: paperless-redis-secrets
          env:
            - name: PAPERLESS_REDIS
              value: redis://:$(REDIS_PASSWORD)@paperless-redis-master
            - name: PAPERLESS_DBENGINE
              value: postgresql
            - name: PAPERLESS_DBHOST
              value: paperless-postgres-postgresql
            - name: PAPERLESS_DBNAME
              value: $(POSTGRES_DATABASE)
            - name: PAPERLESS_DBUSER
              value: $(POSTGRES_USERNAME)
            - name: PAPERLESS_DBPASS
              value: $(POSTGRES_PASSWORD)
      volumes:
        - name: paperless-app-vol
          persistentVolumeClaim:
            claimName: paperless-app-pvc
        - name: paperless-ingest-vol
          persistentVolumeClaim:
            claimName: paperless-ingest-pvc
