apiVersion: v1
kind: Secret
metadata:
    name: paperless-app-secrets
    namespace: default
type: Opaque
data:
    PAPERLESS_REDIS: ENC[AES256_GCM,data:AdbHZClaOFQVA+2m3MQLtNl+Dylt0Hvs5FJNlAQZXKU=,iv:Iw1RBuGFy7N2YFx9nxREhlxPLsoPTp434EspSgAKcTA=,tag:afsVMJb2k1sBEiCgNX8p6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsV0h3VFZMcEhyT3ZOakVN
            MnhoTENtREFkTjZqWENibXdlSFhiRk12blRNCjZteWZWdGxpYWJTNU9KZWNCRCtu
            aGh4QWRQc1BHVVI4VWJiOXR2bWwzODQKLS0tIC80OGJNeWxEUmx0WldZU3duRW1R
            c2huTzhWTW0vUnA0R2ZlNks3MFBONGcKoZzN5oLpNDcV27gtCLsh1kFZXF5dJQ3v
            +3D7DV6/3q+fTTWXTwcIZZywHfiQ8E4vW+Mt4N99QTwfZ6X7OsRvEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T10:14:15Z"
    mac: ENC[AES256_GCM,data:ww+KSqRrny7iWTbYLV5uxTWrcOh26u5DrJBHEcoSL7pBM10GpL4A6WPjKylrRJklsQeipqDfZlHujicRVSCSyIyDhL6kxXsflQHM4KmFf5zDLKisaH0QTpnB7GcH3jlp96oha/4vgGe2gd5OQP6DCmSVWH6y4OsHVoPbkD0XOGU=,iv:9dho+Moz1kas3hEmUuwbeGpAVkfiG48wu1HEG1XXOWI=,tag:99x5nrWGLPDN9ReD4SGlRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
