apiVersion: v1
kind: Secret
metadata:
    name: paperless-app-secrets
    namespace: default
type: Opaque
stringData:
    PAPERLESS_REDIS: ENC[AES256_GCM,data:47PdtvF6JpvGKCVVzJv0e8uiAqLjT21faI21f9Z6Cyo=,iv:sg/dwzwB3yw6xO7/nmRAhW6KOxp3RLyNLKnu+hwiFn8=,tag:/8K5nAYt5wKUQFEKEzjBCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsV0h3VFZMcEhyT3ZOakVN
            MnhoTENtREFkTjZqWENibXdlSFhiRk12blRNCjZteWZWdGxpYWJTNU9KZWNCRCtu
            aGh4QWRQc1BHVVI4VWJiOXR2bWwzODQKLS0tIC80OGJNeWxEUmx0WldZU3duRW1R
            c2huTzhWTW0vUnA0R2ZlNks3MFBONGcKoZzN5oLpNDcV27gtCLsh1kFZXF5dJQ3v
            +3D7DV6/3q+fTTWXTwcIZZywHfiQ8E4vW+Mt4N99QTwfZ6X7OsRvEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T10:16:16Z"
    mac: ENC[AES256_GCM,data:EWI4/+8CnokI8T5hknDStK4MTYOz6/P72twy+0L59iCqLXEbf6ht85mzB7Kk+bRLR3hyiLmAtsQ9DfYr1LmcadMgkVLj4+VcyrgUid9RvKYYajlRvaLCViTJCuMUFM/k9okEMUsDAC+G6CmLKDEZ80onA9hLe60MrMCj9bqCh2I=,iv:IBQnAQllUzXwNZPiGMLjnfgVhYMS6XhwmdgsLqZ9Zig=,tag:m4zFCKibxbS5VBapxxfb9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
