apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: default
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:/gjeovD02DE5y8Q52S4gmTwTI7EDlh/Q,iv:nvog/skU5hrTvkx13T+/O6AYfED7ZTLpEuV6h5Vhp+s=,tag:JBOeuQkEJJ84MnzPdR/QLA==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:ZYEYzd8DtmU0,iv:LEJru//+6pyivSA5WTHrs8c45CbYInZ99wIi4JGSgW8=,tag:dyTdqgO+iP+JYv/4LC7wCA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:62PTj3DmFgaFBlSnQoIZa/OrUfv7Jkoq,iv:JoqtCXQiKIll12cz7oBBBcmYqLolTi1vsDU3cdnEURY=,tag:FEQ3KFZ6LuFrB2uSB5iyTQ==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:ETtV2HBxoWNV,iv:WNiKeJIxog0zsC5XqihpS+Ot4z7Hh+aWXLebpDaxsEo=,tag:BLZqhFxCBk3mxjWquJgVSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VVdGckhOTFFIcGQ1ajlT
            WkVsb2pKeGs4R25IMWR0dU14bnpTLzRGMW5ZCnhlcTFzNW1qdER2bnhvcDRJbE1G
            TllGWlYrU2VZYmIwemo3blZHRk0vVlkKLS0tIGNZdTZvTjdCWlNoN2ROd0UwL3FM
            S244c0lvR20yM3BwMnpyZUZaYUd6RVkK3LJnHjkyIeCZWnYFk/VgLUCyr/HIFaLX
            UKsoT5bIyhwQebI6f/XWdUkEacHyrmk8YipUtEN2WnzsXjvAszGDfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T04:47:22Z"
    mac: ENC[AES256_GCM,data:aGhxIH4xlsIhWaTLhLzJpNz88ZUEFMIpL3TLkpwIkDwERG868lx1Iqxfc0AzSbUDRT8MK4Hi3sEKWYE0AG2iECPma5Ix0aCnIOID7F+kgZK4QXeYLtkVvDKCNXGXRTooVwnGGmzSsJK42O1W/j4c/tV6urmiRVJ3t3aXLZmVS4g=,iv:JIMmlt8lCpav+U5UlLStSW9WC3piYAJp50J7xI1/b9k=,tag:hP3z4ESf1AOkD0RZ3ihHuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
