apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:/gjeovD02DE5y8Q52S4gmTwTI7EDlh/Q,iv:nvog/skU5hrTvkx13T+/O6AYfED7ZTLpEuV6h5Vhp+s=,tag:JBOeuQkEJJ84MnzPdR/QLA==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:ZYEYzd8DtmU0,iv:LEJru//+6pyivSA5WTHrs8c45CbYInZ99wIi4JGSgW8=,tag:dyTdqgO+iP+JYv/4LC7wCA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:62PTj3DmFgaFBlSnQoIZa/OrUfv7Jkoq,iv:JoqtCXQiKIll12cz7oBBBcmYqLolTi1vsDU3cdnEURY=,tag:FEQ3KFZ6LuFrB2uSB5iyTQ==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:ETtV2HBxoWNV,iv:WNiKeJIxog0zsC5XqihpS+Ot4z7Hh+aWXLebpDaxsEo=,tag:BLZqhFxCBk3mxjWquJgVSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VVdGckhOTFFIcGQ1ajlT
            WkVsb2pKeGs4R25IMWR0dU14bnpTLzRGMW5ZCnhlcTFzNW1qdER2bnhvcDRJbE1G
            TllGWlYrU2VZYmIwemo3blZHRk0vVlkKLS0tIGNZdTZvTjdCWlNoN2ROd0UwL3FM
            S244c0lvR20yM3BwMnpyZUZaYUd6RVkK3LJnHjkyIeCZWnYFk/VgLUCyr/HIFaLX
            UKsoT5bIyhwQebI6f/XWdUkEacHyrmk8YipUtEN2WnzsXjvAszGDfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T04:41:39Z"
    mac: ENC[AES256_GCM,data:sB4bcNwUmL9G5KOb9dT8VpK5FdU0yqAhHl3LnNagDkYW5K1ZkCCNVBUpwW7Y9xRJi2eVv5k8G4arqBSdbdKPXM1fzZQ3AgPDPyTYdRbf9yBBXkHsJIyf7AzC9feBPSEMHp7xwsH4lvgeQMaDwRRSUjtZHhxWK0VsOHqFSIlTu8c=,iv:3IPGNYah/EzvZsa/r6IZqckHrzGXeuCFNCfXlu8BON8=,tag:ZV58CHBSOTFhAlx6iNRVCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
