apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-postgres-config
  namespace: default
data:
  primary: |
    persistence:
      enabled: true
      existingClaim: "paperless-postgres-pvc"
  image: |
    tag: 15
