apiVersion: v1
kind: Secret
metadata:
    name: paperless-postgres-secrets
    namespace: default
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:V+CM6a1Afk+1mAsz/z+M8/CmLkoUGVTj/af0DcZ8moifQbwqxvcUrfxZ4MgUXWG1zV7a9nCKwIRcJorXJyb3S5aDAYo7meb1OlZk/228wkGiFBhNijOhoVULXNdNi50=,iv:1vUGC5O+cFTllECDHRz/NnHfIN1jPJpm8gZJgq6sbDk=,tag:BIiyMD5gfZ2nHcYrSUHIQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRmFOMWZ6aFFlcyswUmN3
            R1BJTmNMajZEQW5lQjJXU3Zacm1XN01DbVJrCjg4b3hCWG4xTXlHSVVyOFlwL1RZ
            NUxQVmJBMDVZVFRteHpYR01DOUpaM2MKLS0tIGZOTnVzc21VMGVnSG04aHo1alcz
            RHhLbzhvcEJTQUlwalVaMVZaZDBlajgKLCoV/tfTIayViqC9+AdAziU5CPtxXtXN
            NoobZagMFuXb2t38/FOFDNFYRyXReMDo1JEq6CKfLEDgU4GTO9XMSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T10:30:41Z"
    mac: ENC[AES256_GCM,data:ze2MyHe/Xx68tlc3P1o40LeRmsGp3qemVU+0pQDxZbQy7SeImAMjB2V8I4Iji1bpsdUOqtUZkjqx1c/o/6pINp8fbNg0P1JJLqPUx7aQvDDFRB0itNtJMA3b24AVDdu8/CMGu49l8zj2bVRx2C0KduK6D/LwduGMzl0sBasOzZE=,iv:Xuh/QQdhVg+U/ga91vDND2x8zBSHlYfPkEpPAh/bzKk=,tag:EDu9hidOpz9TOesOzhwzIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
