apiVersion: v1
kind: Secret
metadata:
  name: paperless-postgres-secrets
  namespace: default
type: Opaque
data:
  auth: ENC[AES256_GCM,data:unqJvpLUOwWLFHhZDtzMTX4IMcIU0ToYAQ5v3ZG1IRKD09j8H6drPxvg5TYmkv7JksKW6TP1Ble9UchAs1yQTYFJhQYddHJB/S5UucwTTAXLzcw=,iv:j5nZzSCwJK/ht5EbfmDRf88vwI7OG+O92U4d2G32dEE=,tag:rdrJWbQXsjlcTf7TIQcabQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRmFOMWZ6aFFlcyswUmN3
        R1BJTmNMajZEQW5lQjJXU3Zacm1XN01DbVJrCjg4b3hCWG4xTXlHSVVyOFlwL1RZ
        NUxQVmJBMDVZVFRteHpYR01DOUpaM2MKLS0tIGZOTnVzc21VMGVnSG04aHo1alcz
        RHhLbzhvcEJTQUlwalVaMVZaZDBlajgKLCoV/tfTIayViqC9+AdAziU5CPtxXtXN
        NoobZagMFuXb2t38/FOFDNFYRyXReMDo1JEq6CKfLEDgU4GTO9XMSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-02-18T10:14:59Z"
  mac: ENC[AES256_GCM,data:erzGIKJefnny/NjR4fthkcxx+xyKPfbK73kbwKkyCunyNqIho4W5RLYNL6RMlLua2Q1TJcXlKAcMrrsCWhmF1WP2n4fjY7JBsxOs5c8sFeH9kolOBB4m5g0QINklTm9T5cUilZ0wCr2zv2+H0L/Lf+gwMyztgf38zgIzhoqDRF8=,iv:WS1dQHrILUqT4PG5TfNkwW+UvztNtTfOM1PAzn9jN+c=,tag:jib2QPIkC+gm1NHElt6jsw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
