apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-postgres
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "14.1.1"
  valuesFrom:
    - kind: ConfigMap
      name: paperless-postgres-config
    - kind: Secret
      name: paperless-postgres-secrets
