apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-postgres-pvc
  namespace: default
spec:
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
