apiVersion: v1
kind: Secret
metadata:
    name: paperless-redis-secrets
type: Opaque
data:
    auth: ENC[AES256_GCM,data:JXJVX7dCr6WU1feJf/BgRtkc5YBx+siRv/79e6Td/SbKc853z3Xe2CVcf5CLyRIrjA==,iv:40nB04g/CzRwatpkJP5GYbEBr2CGWRCd74mwYOlwmHI=,tag:dzCsX6GfkL6Ewb55oLqo5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL21mYlZhaFM2bUdaTnFa
            M2NCMEFBYjNhVEZPeGI1VFFaSU5YMnlSOWdVCnJXUUozS3hsRXJWTHBMMGhYQjhO
            clVPMWZtbmFTVVAwNlBvTkRaSUU4UzAKLS0tIHE0S3pKMzF5NWZ6RGZ1YU5zemZP
            bml6YU95cFFJNmpKOWhFeDNJMDBYWFUKERJYPb+oyo9JMKZdjjvAcLCGJ/l/k8bG
            JdhoQ4xihbJsUOUnMWc4pDdtIb32wyxPIKkQmQMQDqejK7ece/fVww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T09:20:16Z"
    mac: ENC[AES256_GCM,data:fgvz1JCSTvOTPzH1XdzJMeJcA1ZLQ5M1XzepoC6y0D9tDvSIeSQCpROr+oUye4VaIPAaSOQeAAFRAYEvRCUnO2n3JjwHEXaSJYCdQy53P7LIIpsScZGMVjVeBJOmFMYrZ2fWpTHpmzb1VlzIH8skv29piN9mc0AJY6qRfpkytSM=,iv:LIcoIIKx/wRq6wFty6CYyegFFDVFOrv1pb0MYqVWjAc=,tag:NNUcfiGKIRZK9uQ9jPagmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
