apiVersion: v1
kind: Secret
metadata:
    name: paperless-redis-secrets
    namespace: default
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:8vvuhKKw3Ng4YZoSSbRKVzD/VQw7eK95oFzgKPPmyM8QTb5FdWbDI7E/ENw3DcI2FQ==,iv:lGrd7Q91oeX2yNq/cWpJYYaLYjr2omH733xg5EvQ0gc=,tag:XJ7V/0Je91OtXxduL0xWPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL21mYlZhaFM2bUdaTnFa
            M2NCMEFBYjNhVEZPeGI1VFFaSU5YMnlSOWdVCnJXUUozS3hsRXJWTHBMMGhYQjhO
            clVPMWZtbmFTVVAwNlBvTkRaSUU4UzAKLS0tIHE0S3pKMzF5NWZ6RGZ1YU5zemZP
            bml6YU95cFFJNmpKOWhFeDNJMDBYWFUKERJYPb+oyo9JMKZdjjvAcLCGJ/l/k8bG
            JdhoQ4xihbJsUOUnMWc4pDdtIb32wyxPIKkQmQMQDqejK7ece/fVww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T10:16:27Z"
    mac: ENC[AES256_GCM,data:kU5PFLpczBmCwvFWqP5ZkqeNmsv2o58HgNn5R0+uccK9Qo9cw19uVAdBfVqszl+IbwB76+lVNHHhcIWspG0AiG1+qWpV3uInsv1KkhUEORGklsd1gUZdgOwsj2dLT0+IpAtlcrWEZPepmL3wBWVEuwUN5vIOt5S/S73KoIVgs9o=,iv:5im32zLvtGANDc/rnXDZx5xfDbGjFyXsHejCltI9J5I=,tag:+lI1W/1XwKxnPC6M/+z8Hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
