apiVersion: v1
kind: Secret
metadata:
    name: paperless-redis-secrets
    namespace: default
type: Opaque
data:
    auth: ENC[AES256_GCM,data:JXJVX7dCr6WU1feJf/BgRtkc5YBx+siRv/79e6Td/SbKc853z3Xe2CVcf5CLyRIrjA==,iv:40nB04g/CzRwatpkJP5GYbEBr2CGWRCd74mwYOlwmHI=,tag:dzCsX6GfkL6Ewb55oLqo5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL21mYlZhaFM2bUdaTnFa
            M2NCMEFBYjNhVEZPeGI1VFFaSU5YMnlSOWdVCnJXUUozS3hsRXJWTHBMMGhYQjhO
            clVPMWZtbmFTVVAwNlBvTkRaSUU4UzAKLS0tIHE0S3pKMzF5NWZ6RGZ1YU5zemZP
            bml6YU95cFFJNmpKOWhFeDNJMDBYWFUKERJYPb+oyo9JMKZdjjvAcLCGJ/l/k8bG
            JdhoQ4xihbJsUOUnMWc4pDdtIb32wyxPIKkQmQMQDqejK7ece/fVww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T10:15:12Z"
    mac: ENC[AES256_GCM,data:WuhXYnrL8MLizFf8QOpUviIUEmp2CAOcqaWT2U4p0VtxD+eTIh0P2UMruoafvTq5CylwG82d8X8lILriy2uRhLP8L1Tv9uuYqC8NQ9+pZngAaDKm/NXIv0l9vX28v5FG6Krm2V1TBJYPzVrtfvAKgg3d5D2nKTUi+1rw+HVmvBI=,iv:YCwoZ6PJ02mSALjWLw89ILSvGvI/btdyC+MLLOpr6mY=,tag:DUosRMkzsK4Dpmh3XZy3rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
