apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: GF_SECURITY_ADMIN_USER
      remoteRef:
        key: k8s-observability-grafana-credentials/GF_SECURITY_ADMIN_USER
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: k8s-observability-grafana-credentials/GF_SECURITY_ADMIN_PASSWORD
