apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        GF_SECURITY_ADMIN_USER: '{{ index . "GF_SECURITY_ADMIN_USER" }}'
        GF_SECURITY_ADMIN_PASSWORD: '{{ index . "GF_SECURITY_ADMIN_PASSWORD" }}'
  dataFrom:
    - extract:
        key: k8s-observability-grafana-credentials
