apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-cnpg
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: garage-cnpg
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        ACCESS_KEY_ID: '{{ index . "ACCESS_KEY_ID" }}'
        SECRET_ACCESS_KEY: '{{ index . "SECRET_ACCESS_KEY" }}'
  dataFrom:
    - extract:
        key: k8s-database-garage-cnpg
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: b2-cnpg
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: b2-cnpg
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        ACCESS_KEY_ID: '{{ index . "ACCESS_KEY_ID" }}'
        SECRET_ACCESS_KEY: '{{ index . "SECRET_ACCESS_KEY" }}'
  dataFrom:
    - extract:
        key: k8s-database-b2-cnpg
