apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-cnpg
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: garage-cnpg
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: k8s-database-garage-cnpg/ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: k8s-database-garage-cnpg/SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: b2-cnpg
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: b2-cnpg
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: k8s-database-b2-cnpg/ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: k8s-database-b2-cnpg/SECRET_ACCESS_KEY
