---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.7
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
