---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-hostpath
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  values:
    # driver only works with 1.16+
    csiDriver:
      # should be globally unique for a given cluster
      name: "org.democratic-csi.local-hostpath"
      attachRequired: false
      storageCapacity: true
      fsGroupPolicy: File

    storageClasses:
      - name: local-hostpath
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        # distributed support is not yet ready for expansion
        allowVolumeExpansion: false
        parameters:

        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    # if your cluster supports snapshots you may enable below
    volumeSnapshotClasses: []
    #- name: local-hostpath
    #  secrets:
    #    snapshotter-secret:

    controller:
      enabled: true
      strategy: node
      externalProvisioner:
        image:
          registry: registry.k8s.io/sig-storage/csi-provisioner
          tag: v3.6.0
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=false
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1

      externalAttacher:
        enabled: false

      # distributed support is not yet ready
      externalResizer:
        enabled: false

      externalSnapshotter:
        enabled: true
        image:
          registry: registry.k8s.io/sig-storage/csi-snapshotter
          tag: v8.2.1
        extraArgs:
          - --leader-election=false
          - --node-deployment=true

    node:
      driver:
        extraVolumeMounts:
          - name: local-storage
            mountPath: /var/lib/csi-local-hostpath
            mountPropagation: Bidirectional

      extraVolumes:
        - name: local-storage
          hostPath:
            path: /var/lib/csi-local-hostpath
            type: DirectoryOrCreate

    driver:
      image:
        registry: docker.io/democraticcsi/democratic-csi
        tag: v1.9.3
      config:
        # please see the most up-to-date example of the corresponding config here:
        # https://github.com/democratic-csi/democratic-csi/tree/master/examples
        # YOU MUST COPY THE DATA HERE INLINE!
        driver: local-hostpath
        instance_id:
        local-hostpath:
          # generally shareBasePath and controllerBasePath should be the same for this
          # driver, this path should be mounted into the csi-driver container
          shareBasePath: "/var/lib/csi-local-hostpath"
          controllerBasePath: "/var/lib/csi-local-hostpath"
          dirPermissionsMode: "0777"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0
          snapshots:
            # can create multiple snapshot classes each with a parameters.driver value which
            # overrides the default, a single install can use all 3 simultaneously if desired
            #
            # available options:
            # - filecopy = rsync/cp
            # - restic
            # - kopia
            #
            default_driver: filecopy

            # # snapshot hostname will be set to the csiDriver.name value, in the case
            # # of local-hostpath the node name will be appended
            # # it is assumed that the repo has been created beforehand
            # restic:
            #   global_flags: []
            #   #  - --insecure-tls

            #   # these are added to snapshots, but are NOT used for querying/selectors by democratic-csi
            #   # it is *HIGHLY* recommended to set the instance_id parameter when using restic, it should be a universally unique ID for every deployment
            #   # host will be set to csi driver name
            #   tags: []
            #   #  - foobar
            #   #  - baz=bar

            #   # automatically prune when a snapshot is deleted
            #   prune: true

            #   # at a minimum RESTIC_PASSWORD and RESTIC_REPOSITORY must be set, additionally
            #   # any relevant env vars for connecting to RESTIC_REPOSITORY should be set
            #   env: {}
            #   # RESTIC_PASSWORD
            #   # RESTIC_REPOSITORY
            #   # AWS_ACCESS_KEY_ID=<MY_ACCESS_KEY>
            #   # AWS_SECRET_ACCESS_KEY=<MY_SECRET_ACCESS_KEY>
            #   # B2_ACCOUNT_ID=<MY_APPLICATION_KEY_ID>
            #   # B2_ACCOUNT_KEY=<MY_APPLICATION_KEY>

            # # snapshot hostname will be set to the csiDriver.name value, in the case
            # # of local-hostpath the node name will be appended
            # # it is assumed that the repo has been created beforehand
            # kopia:
            #   # kopia repository status -t -s
            #   config_token:
            #   global_flags: []
            #   # <key>:<value>
            #   tags: []
            #   #  - "foobar:true"
            #   env: {}