---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sable
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      hostNetwork: false
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          *app :
            image:
              repository: ghcr.io/sableclient/sable
              tag: 1.20.0@sha256:0eada488ac464df4f0f8e25de44f7ccd7fe956add846b66827dcee8a3743e93a
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec: &probespec
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  <<: *probespec
                  failureThreshold: 30
    service:
      *app :
        ports:
          http:
            port: *port
    route:
      *app :
        hostnames:
          - "chat.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-cloudflare
            namespace: network
        rules:
          - backendRefs:
              - identifier: *app
                port: *port
