---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      # renovate: datasource=github-releases depName=immich-app/immich
      tag: v1.138.0
    
    env:
      DB_HOSTNAME:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-app
            key: host
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-app
            key: dbname
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-app
            key: user
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-app
            key: password

    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich

    # configuration is immich-config.json converted to yaml
    # ref: https://immich.app/docs/install/config-file/
    configuration: {}

    redis:
      enabled: true

    server:
      ingress:
        main:
          enabled: true
          className: internal
          hosts:
            - host: immich.${SECRET_DOMAIN}
              paths:
                - path: "/"
      resources:
        requests:
          cpu: 1500m
          memory: 4096Mi

    machine-learning:
      persistence:
        cache:
          type: pvc
