apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llama-cpp-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: llama-cpp-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: LLAMA_API_KEY
      remoteRef:
        key: k8s-ai-llama-cpp-secret/LLAMA_API_KEY
    - secretKey: HF_TOKEN
      remoteRef:
        key: k8s-ai-llama-cpp-secret/HF_TOKEN
