apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llama-cpp-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: llama-cpp-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        LLAMA_API_KEY: '{{ index . "LLAMA_API_KEY" }}'
        HF_TOKEN: '{{ index . "HF_TOKEN" }}'
  dataFrom:
    - extract:
        key: k8s-ai-llama-cpp-secret
