apiVersion: v1
kind: Secret
metadata:
    name: llama-cpp-secret
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:BGGobLvDSAeO/+o4lFc6iBG5m08hPuajJ8MlD71eNehlkX6JEjSRVezp26G//zk1DtOUmi+KuUoOY2r0zJR99A==,iv:JoAO2Sm9FykAFDunyE70LjZSk+HXIrG+LonIxG5/AeM=,tag:7NcZxedSghhqvVYtn72vSw==,type:str]
    HF_TOKEN: ENC[AES256_GCM,data:ZLZBIIRb+Djx3ASwaK/UvNFH10PqU6pkFTAvB6Qyb4G4N59egg==,iv:wO45Wrs10WWd00u0EKIlF5Oz1zglwh+4HAgvLad84FQ=,tag:DUxbkswYLJCED2wq/CJlbQ==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WDlENVhXbDNLZjQ1aFJv
            VlMzRkMvRFFrZTFacHdNUHRWRm5LcjluajE0CjJ5T1FvY3AwN3g2a3h4eE55WVJr
            UENraThsNUZ6VjR5clp4djFsNy9NK0UKLS0tIGNna1hUZURLR2hUcW92d3FrVWtX
            NWFxN2tzSUJLT0orUWtPYTFXZEwyS1EKg6FooowJpXr4xF9S5l3vSYT4HaLjG4eN
            4Iepx+ghDhtJ1d9ednlC7hg1Kl48B3sZs9EmcJqYEzIeLmn4ZDLGsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T02:49:18Z"
    mac: ENC[AES256_GCM,data:xWQ3GQivZnpLgs4dHsBzramFqYHjvqNWIzQKk5HhgxZr+gdbr2IQ5eJ8beKMNP1iQq42OzbQaIyeL/vxNWlxzoAQPZNdva0xAJJfAXDcyLOZFA0e29/SIKRmZl9jSx4wzY5v7Uh7Yf3S2zxLiMJcY8J37xlG5pnAzBjRpeZSjfM=,iv:SaVawRtEAp7+ZOebTutQSB4ZM2SpV3gVMT/c4hisUcY=,tag:IMfdq89TayOp0wxJ6z9CRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
