apiVersion: v1
kind: Secret
metadata:
    name: llama-cpp-secret
type: Opaque
stringData:
    LLAMA_API_KEY: ENC[AES256_GCM,data:gfKFinEvmVaX7mTwunqn/a8+t1bfEttOSFpbC5E04xk8m4WGvqpCUYDH14tJSQqCwU4o3Hxrg28gSzt8xpeYgQ==,iv:1Bxb0UJ/Y94NmP52KpO42Eg+sFIjF+vx/P0sS6d5UUg=,tag:Pz78fEGH2ZGz/sGKHl0wcQ==,type:str]
    HF_TOKEN: ENC[AES256_GCM,data:ZLZBIIRb+Djx3ASwaK/UvNFH10PqU6pkFTAvB6Qyb4G4N59egg==,iv:wO45Wrs10WWd00u0EKIlF5Oz1zglwh+4HAgvLad84FQ=,tag:DUxbkswYLJCED2wq/CJlbQ==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WDlENVhXbDNLZjQ1aFJv
            VlMzRkMvRFFrZTFacHdNUHRWRm5LcjluajE0CjJ5T1FvY3AwN3g2a3h4eE55WVJr
            UENraThsNUZ6VjR5clp4djFsNy9NK0UKLS0tIGNna1hUZURLR2hUcW92d3FrVWtX
            NWFxN2tzSUJLT0orUWtPYTFXZEwyS1EKg6FooowJpXr4xF9S5l3vSYT4HaLjG4eN
            4Iepx+ghDhtJ1d9ednlC7hg1Kl48B3sZs9EmcJqYEzIeLmn4ZDLGsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T03:39:39Z"
    mac: ENC[AES256_GCM,data:flo+H5BT7r3aacObkdsuiitZopUk4+LY6imSo7j16WoJ8nJC/Oy+OF5lSYKgrvduAkyF9yytAo2IarXPHm6d8KF+kWjP/leCGldiL+f5b6D42ZE+q3MEJYquhgNELUHtsnorjRO1+onSl2H4UuPxvBPiarPKKjgivHfgNTs7Gps=,iv:IbmoIOQyo1VY06XDvLRsdpjZmAJO7Uug05zpPtYdAxg=,tag:hUqjgIvS0M/3lYFKy/NeJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
