---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llama-cpp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: llama-cpp
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      authorization:
        type: Bearer
        credentials:
          name: llama-cpp-secret
          key: LLAMA_API_KEY
