---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  repository:
    kind: ClusterRepository
    name: homelab
  credentialProjection:
    enabled: true
  sources:
    - pvc:
        name: ${APP}
  copyMethod: Snapshot
  files:
    ignoreRules:
      - lost+found
  volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=openebs-zfs-snapshot}
  retention:
    keepHourly: 24
    keepDaily: 7
  verification:
    quick:
      cron: H 4 * * *
      jitter: 1h
    deep:
      schedule:
        cron: H 5 1 * *
        jitter: 1h
  mover:
    securityContext:
      runAsUser: ${VOLSYNC_UID}
      runAsGroup: ${VOLSYNC_GID}
    podSecurityContext:
      fsGroup: ${VOLSYNC_GID}
