# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:H+AYRfR0riG9AxR0nGQcB9guvbdZhqWdGNXnZ2yGysMpmzTL,iv:owI3CJEHRwkSFFHqIkqswzlKjCFnn+OItrcdeUoQcws=,tag:GpcNxCt5ZqpDvKznN2cj2w==,type:str]
  credentials.json: ENC[AES256_GCM,data:jBRC7C/kXj0YD+Y3Ap503aeyQclNmjv5XJdTYVayXPhnXWmjYk7ke7xK27x9a1e/fp+U2COY4MqHNKB37HptAdsEXQ91uMYZM6hveg87QzlGo3XUfqMQGA4FVPxrN71ScLVw6jYN1iY857YdEePHm6njbo/CpfSEqYwhJ1pgBv40WNwYdo/3IgDRMYqHIVxtbA2ltJyduMOpD2uUxajeswRmZ2qzuDqZ8smm0KosBg==,iv:3O7oAPpLMYEWWUVETxiQ5SYAwD2rdxImceI9SUS9zoc=,tag:AANszYOBGpm6WWB+nq9kXg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hkggfdsuse44s5aw3wulvq45h9u93lgvgarm8leqxnesf6knyffsgnh78f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBic2NPN2hUdVZvV1hwZEZX
        cXJDRUMzZ0JiOG1UU2pCRzBFejJsaHBTMkZnCnpnaW9kU29DL0tkeXkrUmkxSnV1
        ZWxhLzMzRG9FY2tEcHBOaFZERUs4QncKLS0tIDFVTjJVeisvL1VhZ0JNeC96RG1W
        TEdOcDVEdzZta0pVZW13K3pJVlBEYTgK1IzcdOoxN9EUJCrx7xnLNpD1B5SJ2oU0
        W89XO22/zYdiBx7PCZMsSSHXCbJ6vwdpGrqQzVAjt116I8IX9UMPaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-25T22:00:11Z"
  mac: ENC[AES256_GCM,data:Po3EVFknLR+K9wqrYMfvKFjAhNqI8q8bAxwLS/+Yzm2M4oOrl5JSUd7us+BES1wJ7w/srQ4xuLq63C4YDUoDjkm58v/vpqIAcuo1NjOeCe3HmFMZdzzFUZprJAiJ9y8KyhBfik5K4twuWz5RjRP0+b3gKpHS93gRANc8qIYtTaI=,iv:X95Xb/JbJJs64sMrN5950+ThMA1OEanjOn285SoiybM=,tag:3N4iwMyNWaZVcbnkaSS+kQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
