[env]
'_'.file = { path = ".env" }

[tools]
pipx = "latest"
python = "latest"
task = "latest"

[tasks.deps]
run = [
    "pipx install --include-deps ansible",
    "pipx inject --include-apps ansible ansible-lint",
]
