[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }

[tools]
pipx = "latest"
python = "latest"

[tasks.deps]
run = [
    "pipx install --include-deps ansible",
    "pipx inject --include-apps ansible ansible-lint"
]
