creation_rules:
    - path_regex: .*\.sops\.ya?ml|/dev/stdin
      encrypted_regex: ^(data|stringData|email)$
      age: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdUVOUnNwczk5RjhQK3Rp
            SFFDMjZCWkk1YjdlN1duU0VUclpPb2ZXRlZVClZHNmZDZ2tjbEtUU2szc3FTYSth
            WEF0a3U0ODVwY2dEVnNDOW1jWXQ2QnMKLS0tIGJIQTNEVXE4SkxTL29OQXhxOWFK
            UUJzekc4d1JXbmQ1U3EwVkIyVnRIT0UKQnWSBU3s9VMNRFITBwkC6z09qV+FvPIn
            /+v3Gr7tWk5Fv0pqzQUQFhyYq0ki8SSCTS/Ysbd8vyM4FVJFcV5nsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T04:37:11Z"
    mac: ENC[AES256_GCM,data:r88DOBeGwD5LNbTaSacMnKQV2tM87s5VxiW9HKTOMwxSXfpFR8fY3JlknbGAHJzSm4de0lSmIhRJeNKo6HFgOKJGm2D61ThS5Vyo10A76k3NPJjbLqHGf6cOPgfUVt4/1JXX8MR2IMc0cgPnVIyO9DhEh5cSyJ8/kzCjkbvXrWE=,iv:3KWUM/28lX0xtxudBUnBKhgLJ2KEwMgONtzNq6IlOwE=,tag:kUeiE82wiTB1cH/+2QE03A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
