creation_rules:
    - path_regex: .*\.sops\.ya?ml|/dev/stdin
      encrypted_regex: ^(data|stringData)$
      age: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdUVOUnNwczk5RjhQK3Rp
            SFFDMjZCWkk1YjdlN1duU0VUclpPb2ZXRlZVClZHNmZDZ2tjbEtUU2szc3FTYSth
            WEF0a3U0ODVwY2dEVnNDOW1jWXQ2QnMKLS0tIGJIQTNEVXE4SkxTL29OQXhxOWFK
            UUJzekc4d1JXbmQ1U3EwVkIyVnRIT0UKQnWSBU3s9VMNRFITBwkC6z09qV+FvPIn
            /+v3Gr7tWk5Fv0pqzQUQFhyYq0ki8SSCTS/Ysbd8vyM4FVJFcV5nsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T21:06:03Z"
    mac: ENC[AES256_GCM,data:40iQvq8ph8QFYfd66OttK8kxJL4TimAp6MPPYP1pi8MVk9Flp0JCPfQCEW4PMrXgZw19XRjgau2YEIckCG9+oNbuYPQNG0ynx9KaadlTLPyMGJC/yMPSBCcWXug959+/5hpQwx8EdB7Ywx68FnP4Keqa6/4Y+nqESrs4Tf4HEIc=,iv:zD6+3IXsyXXIVxFUqiXz5oty8/cjFuU5RhR1Q4bi+jY=,tag:7D3op4G8gbLzq04Ok9Pdkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
