version: "3"

tasks:
  brew:
    vars:
      INSTALLED:
        sh: brew list --full-name
      PACKAGES: >-
        bash-completion
        go-task
        ansible
        ansible-lint
        fluxcd/tap/flux
        ansible
        kubernetes-cli
        k9s
        helm
        age
        sops
    cmds:
      - for:
          var: PACKAGES
          as: PACKAGE
        task: .install-package
        vars:
          PACKAGE: "{{.PACKAGE}}"
          INSTALLED: "{{.INSTALLED}}"

  .install-package:
    internal: true
    label: "Install {{.PACKAGE}}"
    cmds:
      - brew install "{{.PACKAGE}}"
    status:
      - echo "{{.INSTALLED}}" | grep "{{.PACKAGE}}"
