# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:yy71ET6W/zywKljlkJPX6GC8qB6fOSBUja5ZjUYWVSk=,iv:NC3Ub4HZqvHj/kR0U/UxtWoFTvw9w01TjPEKN4HMYT0=,tag:yxkSITlznBX2JA0G1IgMBQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hkggfdsuse44s5aw3wulvq45h9u93lgvgarm8leqxnesf6knyffsgnh78f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWGM3TFRIbTVMQndmZjM2
        TEFUSkdrU3VyUFJMcWZLeSt0eXpnTjEvK0VVCkR2bHppL1RmelBDOURCbkI0K0xh
        R1BuOUVMSlN4TXJneGxJV0p5SEgxeWcKLS0tIHViSVFMRjl3clNhckxOOWtHWURI
        WlZuSCtqTll0YW1HVTArbXYyTFlQQU0KsQ1VO9JdG/rHAyc4DSO52PtTZghEwnaQ
        i53b57ghZOorgarrzL4hUr+da38bTnkitPDB8jkRiaHc7SLK25filQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T04:28:32Z"
  mac: ENC[AES256_GCM,data:ylw5z5URXZfqD/6T7eO4maMHqvc367HNTlr75Az0a2HPIWdBw8/2ReINwKFx6RjfSo9mCv1eTNFQKIIZD30Lop1Ow+XA6s12f/Qxie74XOf69CJbKAZ0q/AAbKvCttSVXZxtZA+nxb63tYz3TMjdId3SorIhqmUgWNBg52fbUwE=,iv:RSAXPd8Qz+PApmvqh2myYZ4hKrPZJdsNXQpRz/SVZv4=,tag:d2pccypiWX6tI+4f1dPfNw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
