apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-postgres-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: seerr-postgres-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "database"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  data:
    - secretKey: username
      remoteRef:
        key: k8s-media-seerr-postgres-secret/username
    - secretKey: password
      remoteRef:
        key: k8s-media-seerr-postgres-secret/password
