---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app seerr
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          *app :
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: v3.1.0@sha256:b35ba0461c4a1033d117ac1e5968fd4cbe777899e4cbfbdeaf3d10a42a0eb7e9
            env:
              TZ: America/Detroit
              PORT: &port 5055
              LOG_LEVEL: info

              DB_TYPE: postgres
              DB_HOST: postgres-rw.database.svc.cluster.local
              DB_PORT: "5432"
              DB_NAME: seerr
              DB_USER:
                valueFrom:
                  secretKeyRef:
                    name: seerr-postgres-secret
                    key: username
              DB_PASS:
                valueFrom:
                  secretKeyRef:
                    name: seerr-postgres-secret
                    key: password
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
            securityContext:
              readOnlyRootFilesystem: true
              capabilities: { drop: [ALL] }
    service:
      *app :
        ports:
          http:
            port: *port
    route:
      *app :
        hostnames:
          - "seerr.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: *app
                port: *port
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/config
