apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: seerr-postgres-secret
  labels:
    cnpg.io/reload: "true"
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: database
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
  username: ENC[AES256_GCM,data:kb6FrDs=,iv:no5Y4/GGK5fKq/wFUYxsF/Uc2jGlHwnBWkTo4pOaE1g=,tag:32HgC1TReKngC8Hdy+W1pA==,type:str]
  password: ENC[AES256_GCM,data:1HGX3ZNos48SI3Tt7LShGt+NKPqaXuC9vJsheZL8oVV/99n8nY2vzQrmwOgUwLdG8nrE7vU0HwfesRrP2DPa0Q==,iv:zt6Qeu5lPKTcAkIdMebihOUbumIX2FVDuE5ClV3xKuQ=,tag:F3N9WXxpx6rEvKzwsl39OA==,type:str]
sops:
  age:
    - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZFRKcWlnN2h4bTJIcmZp
        Vmk1ZTFLTm5HeXpVWFNOcmlJL2kyYmdLbVg4Cm9ZU0hudnc3MGtyUkwxTUZxend4
        bjJqbThiOGlheTJaYlNlVk56cHRVbzAKLS0tIDl1SW5KODNvZWZRM01pM0o0YXV1
        QUhPcXYxN0oxSS9jeC9FOGRPNWEyQTQKS6NcK815bSqZNKd/f3ASDuohYZvOP7KN
        vEJSai0OqvCfkvvDOwCA2GEc70ukgOZ9EwfOYPelBGS/3NEw+UqXvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T15:27:22Z"
  mac: ENC[AES256_GCM,data:Qq7zGH96pAzFc5XpcMSq3FqXRPz2e3djreJJ1quRSEitJAZSt+mpe16HHBZjpIZ+QK+B5be4nP8+Ltlaq7Om/GSJsgOZ6n2eAieGL5KMMVeWJuAV9Vb7J5SN1XJsekik2MWWKaaVf5apURWdRDPKf5hZF1PjJA1UDjwheOtmpfw=,iv:HVEY1dEb94fkPPaud9+ku2qipC+ki4d05zObte6kfzo=,tag:AN9Fh+yBTHdbI5KcYFO8zw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
