apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sabnzbd-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: api_key
      remoteRef:
        key: k8s-media-sabnzbd-secret/api_key
    - secretKey: nzb_key
      remoteRef:
        key: k8s-media-sabnzbd-secret/nzb_key
