apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secret
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:cn4JDeAkbfehz34N1OkBadAKbYgPVcwksHUrb4EoOQNJt+bsfgF+HXdsJEVVcTUcpF0QXhK0aburH9HaZKnOYg==,iv:XFMWq6/Ka2WZKWMiUpI0r+7dAjxxRtDSTrb2EqajohY=,tag:W1uu1QkwPCF8uhesZcCXtw==,type:str]
    nzb_key: ENC[AES256_GCM,data:O/zAJrVbMYsPzdvvou+BMR3Zb9ywodGu83b1escUJghNiOxwRnXIx5DrwJ8HbnLTmX4mM+cJk5Q/TD1k6ABqbQ==,iv:U7tFwlNhBQz3+ibnfExcPOf8yU2FNxIdTqRo9Z5hv5E=,tag:g17bps9QR7ocGyXGCytYSg==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QjNBSm9kNzFVbThQazFk
            bEJ4SmpFcW1Gdk96Mnd1cEp2TzFvTW9KUFVvClpYeHBGb01KVmdQbmV0WXZ2U1ZE
            blZybjg2RmFuZzZlNStmbTY5Vi9VWDgKLS0tIEdST3BWeUN4QlNZQjdvTXlQaS9Q
            WnI4OVhNenZUVDV2ZytzZG5DdjNKeGsKph0e666H86gCrdjyi40Za2BNPflKg/0X
            JWn6ZeHRru2aX+m0qaVOxnPu6gprQP0EOETv/HVHLOZixrtWjl4GEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T14:24:58Z"
    mac: ENC[AES256_GCM,data:FP0GZ7Pwgx0YFNnR+mUjpx/LwYA/CJv+ovaFtFo8GQYLyNJ2yf3nOxrblC/2usJwd8QbxHATkmnwWW5gGqje1zX79R1yyYAnvY2Oa9KurDg5o0dwD4GPsAQbKQFLDNgdHDoslO4BuH2n6tZOBrgzMTAzZtm2KTM/Y0822dCHcsU=,iv:33Uh8EfGC7V81zPpG3It/fau2CzqTBJd/5VgW/DtmHs=,tag:ejqNkAqz0FyD1Zhf3U19zQ==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.12.1
