---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../variants/base
  - ../variants/envoy
patches:
  - target:
      group: pocketid.internal
      version: v1alpha1
      kind: PocketIDOIDCClient
    patch: |
      - op: replace
        path: /spec/secret/keys/clientSecret
        value: client-secret