_:
    @just --list

# Create a plan for the current unit.
[no-cd]
plan:
    terragrunt plan -out plan.tfplan

# Create a plan for all units.
planall:
    terragrunt run --all plan -- -out plan.tfplan

# Apply a plan for the current unit.
[no-cd]
apply:
    terragrunt apply plan.tfplan

# Apply a plan for all units.
applyall:
    terragrunt run --all apply -- plan.tfplan

# Format all *.tf and *.hcl files.
format:
    terragrunt hcl fmt .
alias fmt := format
