backend:
    access_key: ENC[AES256_GCM,data:5fjpmfyM7m3luJgfSWBSfes/r6WPXDYGCQs=,iv:t4OX7CY7VFeR3BM2neTxGKElcAGicq7DcfWg4Mav7yE=,tag:5Ur/2Viqdp6SnVdG/QM2uw==,type:str]
    secret_key: ENC[AES256_GCM,data:MEaIyDPP1J2QnSQ9K2R02V5THXES1l1NNGU1V2eddBYZvBNPX793+Qrl6xDoC+vwPdZpMT9kD4FkcLdjHZ7PxQ==,iv:Ufe7TnKZzpFqv05RLv9LCOdF1CIR/3Z5aRGLYAcn244=,tag:wjVQgQHlFSNJVJM8ud4URQ==,type:str]
    endpoint: ENC[AES256_GCM,data:6ntoMMqS3mf2RBA+eirFUb9utIHAfQ==,iv:yFaOOA9Jj8KX2MVb6ZWF1xZGCI9OfxUGc95KKLBji1g=,tag:UgZ5T3czmwg+44wAqmrdpA==,type:str]
    region: ENC[AES256_GCM,data:sHMyJCHE,iv:qzpvasklDfyH7VKkXeQlCKRMc3ze3sxDWztSvgAloCM=,tag:Iy2ype3+4Z5eNCQy9ftPvQ==,type:str]
    bucket: ENC[AES256_GCM,data:co81rkgOfA==,iv:w2bCr0U88kVvJWCMDGTWs0UcaJodWKnDFh7WQbMpLZo=,tag:jWcTTO0SEz95kX6fHi6zig==,type:str]
sw_core:
    host: ENC[AES256_GCM,data:qWtx6o8LFp8q2qW+LvB1YEH+kg==,iv:KwK97ggyT0688D31z6fE9lwmjwUo/MZzFxDkYKBjbyM=,tag:7eEu7dsV8uo6h9FNh28tvg==,type:str]
    #ENC[AES256_GCM,data:TjsyA2WMQjrbF+yB5y3H+0npzK6zTHDe,iv:9wo2f0B9LMjgfzyocbOstQIvcgvWNvjuE3FTan3hTzg=,tag:LZ6hba3ymeR7YF8LRuPX6A==,type:comment]
    username: ENC[AES256_GCM,data:QTQRFxw=,iv:meZ1Dz62xs4NgWbmdw6grEmAG7BjE7Gf1vNm+kUSdVs=,tag:GxVv4p7KpOkfBzGk5zk0jA==,type:str]
    password: ENC[AES256_GCM,data:buBBcZXsi2M00HyP8WK4jFZivw==,iv:CMa7huelmjZHweuErsImkc+S++jFe6UjSpH6VXHlzBA=,tag:K5sXgUtxJf92CRhzC4rmgA==,type:str]
    insecure: ENC[AES256_GCM,data:c4wY+A==,iv:Nmiiq5LvVv8ZfkUgR+x3jl8LYk7GVrowO3eu9ulM5Ec=,tag:P3QstSriAYI0ZMb/kFNuoA==,type:bool]
backblaze:
    key_id: ENC[AES256_GCM,data:ZSQp8p30cVClUEWak2sTMx7YqAG3oDVtHw==,iv:yfDYNmLwyH7P0Q/G+Aqmrn5GfNT72s4QvYVEkToOj78=,tag:jKthicTBkfjiussAjhRxCA==,type:str]
    application_key: ENC[AES256_GCM,data:/5tpr5THQpC7JWKq3ary16+2q42xCnYj4BifJ8584Q==,iv:87x1KH3PHkrEqrCOzmopQzWUt0cO1CJ4Z2yWqEjqWQg=,tag:eOBIEWOf6f6tcfRoNYC87w==,type:str]
    backup_bucket_name: ENC[AES256_GCM,data:SLYTyub5yahoJnnhn9etzQKcIA==,iv:9OQmnHhYcv9pLlgA7X/PYGQEYczXopmNOhEo7mIWeUE=,tag:0QeaftWt8Zk85sAX7jFMTQ==,type:str]
migadu:
    username: ENC[AES256_GCM,data:c1n7WUiHxdMwsknHJsLAMNWR9Cw=,iv:YfEHuA4GFupjPjsrSzTXdiqnFsQx9YjbkhVo7qJYmhY=,tag:tapRZ3TWFHIA0POW77ENXQ==,type:str]
    token: ENC[AES256_GCM,data:06Dq8GXOvANh9yrpuEfyXQs2aEXC7X0usrQebPe8DQ74iaa87Xk5ChDWxRGBE4SYN2ZlDjcIdpMDt3oSndAqq4DudYZwxLjl3odXwCBJU6SRbc018Ds=,iv:fOSqJPjOFMhAy5qk+UIcD8PcrsR/hDCqBonKHGCm+1o=,tag:LDqdt2bjVhai1YIco0TzKw==,type:str]
onepassword:
    account: ENC[AES256_GCM,data:6CGPMsI2zb4I4WU=,iv:5Ujz6Glph986na/GUGVT6DOMd8/jxP1h2Kw+jFyYzV4=,tag:rmnV9hYOJCcWLCwGyH0oSw==,type:str]
    vault: ENC[AES256_GCM,data:bbmCHY/iKA==,iv:B/mjuots0UwU7oYgR3MKG6i1Qr5ZDl8driDx6VYjFFQ=,tag:pEAE2KBHOkODLWSBVkvb5Q==,type:str]
domain: ENC[AES256_GCM,data:UiVrNeBfvrkn58Y=,iv:NagblUrE/LRgYopu5QZZCovZLewQ+abEr2Pny4p8s3g=,tag:xUupC4kjvNslbklB8ffm0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWWQzMDdDWUpacTNnQ1pm
            NXZqUStGb0plNkpxdEhhUWxpdkNlWjQyK1VBCjdKb09GaHFDSDBqUXRhSUVxdVVl
            NGt2YU83S0FNU0M4MHMyNGpkYUUyZk0KLS0tIDBlTVhzdUd5cUhlRHd5SGFvYldV
            VXF0WlRjMWwzNXNGVjRueGVvWDNxK3cKxHzM3/LSFg9NJAKC8lFOxKnwCpw3jDYT
            +luoF4GfFBUy/i8p5ylxMvhea0aLbyox5lcUpZ7Vls7eZlNL9TB6DA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
    lastmodified: "2026-06-06T17:35:36Z"
    mac: ENC[AES256_GCM,data:BO2AFVJYKzDkuCHCydy6UwipU+TLCKTurYP3OPaKrt/BhvJ6DrYS0hFHT6MhRmQ1wYq0RQZDua/tHUVyIM7nL36MH+U2o7eBE6CZlx8kB3HicDvpKy2vpY4jNF5IMRVInYCjVhLRcgezYoFFu3qvgr9p0TAvwNNxdDiJM9rCrYk=,iv:rk94or8/0socqe9ZkNteCHOCcFZV77rSSH1uL8YIZyA=,tag:8rpGwvPj5guMvoQDyS2SzQ==,type:str]
    mac_only_encrypted: true
    unencrypted_suffix: _unencrypted
    version: 3.13.1
