backend:
    access_key: ENC[AES256_GCM,data:5fjpmfyM7m3luJgfSWBSfes/r6WPXDYGCQs=,iv:t4OX7CY7VFeR3BM2neTxGKElcAGicq7DcfWg4Mav7yE=,tag:5Ur/2Viqdp6SnVdG/QM2uw==,type:str]
    secret_key: ENC[AES256_GCM,data:MEaIyDPP1J2QnSQ9K2R02V5THXES1l1NNGU1V2eddBYZvBNPX793+Qrl6xDoC+vwPdZpMT9kD4FkcLdjHZ7PxQ==,iv:Ufe7TnKZzpFqv05RLv9LCOdF1CIR/3Z5aRGLYAcn244=,tag:wjVQgQHlFSNJVJM8ud4URQ==,type:str]
    endpoint: ENC[AES256_GCM,data:6ntoMMqS3mf2RBA+eirFUb9utIHAfQ==,iv:yFaOOA9Jj8KX2MVb6ZWF1xZGCI9OfxUGc95KKLBji1g=,tag:UgZ5T3czmwg+44wAqmrdpA==,type:str]
    region: ENC[AES256_GCM,data:sHMyJCHE,iv:qzpvasklDfyH7VKkXeQlCKRMc3ze3sxDWztSvgAloCM=,tag:Iy2ype3+4Z5eNCQy9ftPvQ==,type:str]
    bucket: ENC[AES256_GCM,data:co81rkgOfA==,iv:w2bCr0U88kVvJWCMDGTWs0UcaJodWKnDFh7WQbMpLZo=,tag:jWcTTO0SEz95kX6fHi6zig==,type:str]
sw_core:
    host: ENC[AES256_GCM,data:qWtx6o8LFp8q2qW+LvB1YEH+kg==,iv:KwK97ggyT0688D31z6fE9lwmjwUo/MZzFxDkYKBjbyM=,tag:7eEu7dsV8uo6h9FNh28tvg==,type:str]
    #ENC[AES256_GCM,data:TjsyA2WMQjrbF+yB5y3H+0npzK6zTHDe,iv:9wo2f0B9LMjgfzyocbOstQIvcgvWNvjuE3FTan3hTzg=,tag:LZ6hba3ymeR7YF8LRuPX6A==,type:comment]
    username: ENC[AES256_GCM,data:QTQRFxw=,iv:meZ1Dz62xs4NgWbmdw6grEmAG7BjE7Gf1vNm+kUSdVs=,tag:GxVv4p7KpOkfBzGk5zk0jA==,type:str]
    password: ENC[AES256_GCM,data:buBBcZXsi2M00HyP8WK4jFZivw==,iv:CMa7huelmjZHweuErsImkc+S++jFe6UjSpH6VXHlzBA=,tag:K5sXgUtxJf92CRhzC4rmgA==,type:str]
    insecure: ENC[AES256_GCM,data:c4wY+A==,iv:Nmiiq5LvVv8ZfkUgR+x3jl8LYk7GVrowO3eu9ulM5Ec=,tag:P3QstSriAYI0ZMb/kFNuoA==,type:bool]
backblaze:
    key_id: ENC[AES256_GCM,data:ZSQp8p30cVClUEWak2sTMx7YqAG3oDVtHw==,iv:yfDYNmLwyH7P0Q/G+Aqmrn5GfNT72s4QvYVEkToOj78=,tag:jKthicTBkfjiussAjhRxCA==,type:str]
    application_key: ENC[AES256_GCM,data:/5tpr5THQpC7JWKq3ary16+2q42xCnYj4BifJ8584Q==,iv:87x1KH3PHkrEqrCOzmopQzWUt0cO1CJ4Z2yWqEjqWQg=,tag:eOBIEWOf6f6tcfRoNYC87w==,type:str]
    backup_bucket_name: ENC[AES256_GCM,data:SLYTyub5yahoJnnhn9etzQKcIA==,iv:9OQmnHhYcv9pLlgA7X/PYGQEYczXopmNOhEo7mIWeUE=,tag:0QeaftWt8Zk85sAX7jFMTQ==,type:str]
pangolin:
    compartment_ocid: ENC[AES256_GCM,data:JmAsgM8IfcoFbCkaa2UKFe0wiJ3ZHcvLwea+TY8EVLOBTyVMBa+AMsjChpprMrJNTMzY2SnKBninkOxHJLqnir2Y2QQ7MN2+TW+GgbZeag==,iv:IjypFpx+HhLHnOdOwgDV66v6nVxJMgnkMblslQUYYBY=,tag:4yACKkqCHDmP7WqrjaRhxQ==,type:str]
    region: ENC[AES256_GCM,data:LSXTLh4XS7ETK1ri,iv:ke9pXoh1mFaQeUVFHntZNND31yENMNnoAB2AxHOtlBw=,tag:EyIkuZKcEe9W9M1d65qOXQ==,type:str]
    ssh_public_key: ENC[AES256_GCM,data:6z2SA1N5bd4vrwqPhZ50s8rSvlThqoziva3Sg3ech76Q2z8n2qp3F1Z6mvmMbEong5BcbeOdCoiUhCw/IYn4UUjQZhYlOyvUNpnF3f+Unjw=,iv:v5EZFUOma5CrPFJeG1t2DeHIdwkZfj8CZ/nFoKXuP38=,tag:Dwp+RKjj8IBIKMJ5xn/uKw==,type:str]
    availability_domain: ENC[AES256_GCM,data:vevacqp9dnFCFRkdH8V5cxT9SAicEA==,iv:Ia+s09PKTgta33927Kqbf969Vcifa/YJMrnSmcwAV+c=,tag:Iszr8VPqeupyY5+CEeS8lg==,type:str]
    cloudflare_api_token: ENC[AES256_GCM,data:6nsaHYticPfY7Qn3a4K887V340hVKBOCSWwKd/HiMQAtJHD6/QMxaw==,iv:sWk7+QFw0aS5i44EE8+qHIOD0EfbBk1643+d+f+iWaY=,tag:KBa09peaj1jRQUwm+D0KtQ==,type:str]
    cloudflare_zone_id: ENC[AES256_GCM,data:682z99ec7Y/Uk1c1xdPLXjKm8YoOwQ6jstDk7owZ9YQ=,iv:AYFnrU4WvBOOTlYY0V/APhB/PdCp8+NZQmtYHtSkeiA=,tag:YEVlY6w1J3KmiFqc3TtHjA==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWWQzMDdDWUpacTNnQ1pm
            NXZqUStGb0plNkpxdEhhUWxpdkNlWjQyK1VBCjdKb09GaHFDSDBqUXRhSUVxdVVl
            NGt2YU83S0FNU0M4MHMyNGpkYUUyZk0KLS0tIDBlTVhzdUd5cUhlRHd5SGFvYldV
            VXF0WlRjMWwzNXNGVjRueGVvWDNxK3cKxHzM3/LSFg9NJAKC8lFOxKnwCpw3jDYT
            +luoF4GfFBUy/i8p5ylxMvhea0aLbyox5lcUpZ7Vls7eZlNL9TB6DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T22:49:25Z"
    mac: ENC[AES256_GCM,data:cSRu4+OQTdgOIt/lGj98X+1O74gFiiqh+YOWFqNyUAsXgoacKd8znfEolyv3bxL1qyjK8a72nAdu5mI8PfTpQeLoh+zKWHa2KViVXGTxZ4Iknu2jPX82ud9BwIeR8v5aWQ2Hh2kDFor1ez17F0/uc9GdM5RnRTQm49gCNYGiLuM=,iv:0SsjNS1nvYM8hmkg3ZkuN2d526K97T602UnmMF+uMNc=,tag:A4JCOh0ATXEt07HbgJX/cA==,type:str]
    unencrypted_suffix: _unencrypted
    mac_only_encrypted: true
    version: 3.12.1
