version: 3

tasks:
  init:
    cmd: terragrunt run --all init

  plan:
    cmd: terragrunt run --all plan

  apply:
    cmd: terragrunt run --all apply

  format:
    aliases: [fmt]
    cmd: terragrunt hcl fmt

  auth:
    cmd: oci session authenticate --region us-chicago-1 --profile-name DEFAULT
