---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pocket-id-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        ENCRYPTION_KEY: '{{ index . "ENCRYPTION_KEY" }}'
        mailboxPassword: '{{ index . "mailboxPassword" }}'
  dataFrom:
    - extract:
        key: k8s-security-pocket-id-secret
