apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocketid-postgres-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pocketid-postgres-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "database"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  data:
    - secretKey: username
      remoteRef:
        key: k8s-security-pocketid-postgres-secret/username
    - secretKey: password
      remoteRef:
        key: k8s-security-pocketid-postgres-secret/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pocket-id-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: k8s-security-pocket-id-secret/ENCRYPTION_KEY
    - secretKey: databaseUrl
      remoteRef:
        key: k8s-security-pocket-id-secret/databaseUrl
    - secretKey: mailboxPassword
      remoteRef:
        key: k8s-security-pocket-id-secret/mailboxPassword
