# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/refs/heads/main/dist/schemas/pocketidinstance_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDInstance
metadata:
  name: pocket-id
spec:
  annotations:
    reloader.stakater.com/auto: "true"
  image: ghcr.io/pocket-id/pocket-id:v2.6.2-distroless@sha256:a9adc636b5d30098307b8a1292c5887a59690cd5429aac5e87b588852f9c346d
  versionCheckDisabled: true
  env:
    - name: TZ
      value: America/Detroit

  analyticsDisabled: true

  encryptionKey:
    valueFrom:
      secretKeyRef:
        name: pocket-id-secret
        key: ENCRYPTION_KEY
  databaseUrl:
    valueFrom:
      secretKeyRef:
        name: pocket-id-secret
        key: databaseUrl
  hostUsers: true
  fileBackend: database

  persistence:
    enabled: false

  logging:
    level: info
    json: false
  # todo: service monitor for this
  metrics:
    enabled: true

  auditLogRetentionDays: 180

  appUrl: "https://pocket-id.${SECRET_DOMAIN}"
  route:
    enabled: true
    parentRefs:
      - name: envoy-external
        namespace: network
    hostnames: ["pocket-id.${SECRET_DOMAIN}"]
