apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: pocketid-postgres-secret
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: database
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    username: ENC[AES256_GCM,data:+Vfs0DVqOxs=,iv:89yc/dowy4COefA8LLUdkWrm1zK47LLSqn3mm80xEcs=,tag:F0IrdkX9MDR1JbOhysJrfA==,type:str]
    password: ENC[AES256_GCM,data:akS7cnH5Tr/7B5EJ8HzS6U/t55fDFhlL3IE/6BdJ14NDF41cFu5Rwf0vzTYzW+yVP2LwvgSjsnqXUXhL/BSlDg==,iv:KxAga4sHr0Pl+dYrOkLQm6iOLhBTaPtrnorJb3q9ujE=,tag:EsvBNlH8kNZ1qxx2RKkFuA==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eWdsS2FlaStSZ3FiMExm
            d240citwZ0x6dFNDVlBKUG5YT1M2MXNLWlRNCmlkcUVIMkZvSTZwZUZObWxESFNz
            c0VzRHhra0d4RnFVNmxGTGNNTlhpQk0KLS0tIEh4OThVU1cwQVJFTm9ORDYvMXZL
            cTdrOTBTZUdPUkF2NWxMRFdHOWhLMXcKntK4DJlexxLmXpOm72Mscd2mV7ZWAWIQ
            LaZfMcB4keDCoInzgk5ACx+XbU2Hqsz24nH88CQZfTfZHye1KSbtuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T07:33:52Z"
    mac: ENC[AES256_GCM,data:ZrIaZz5mdoXAYmt4kwBscF6uxTL3HJ2cj8q0A9qSCzXQrZXbnM9Nbzbv164pDWfJxpZOYEl5DAnEYBdG00h8idy6uBVQ50v2A1k9iHyod7ZhLJ3pPR/Ea6ccoBJbGCcO0D4nHbcwRIL5TxEvkfLckyUTh41w63aKvr7ngDlB+Yg=,iv:xMflFdLCk9+Z4/itkIPa788zDQLrlN+hXxCIRHz2chI=,tag:0BsoFiQk4Z0R7SJ3Z9fyVw==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:iSi86w+/9aRGG0M0RlZrM/r5NIDLRUWiVFFOdXYvG6UfGjc8mrZnHQzYuRI=,iv:9woDKkQBstSZZR/lfkKoY5VERbRXvtXDW6JdRq8Oa5E=,tag:sM4I6jWuHVODo4xDMRkySQ==,type:str]
    databaseUrl: ENC[AES256_GCM,data:YZOomqtgyVt4g1agclpPo8IdwUpJD+glVtRv3fENE9QyG0YUP8yoEzMtJyPH5jx2ORKa1iU6gaPZbVWDTWe0CHTNJlaKXqD+16jq4+TNlSniB55NRoY7YgdaJSbwajBJ9rIFz36zWEXNDJ5L/TczopVoRMLHg/KdKMVAPSZpju2lWQHQ,iv:RbiL9Ho3j+ARiYY8mAawwtawthrSSxHcA7+JANIPjUY=,tag:TLExzecgRHYQXLbTNLPLxw==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eWdsS2FlaStSZ3FiMExm
            d240citwZ0x6dFNDVlBKUG5YT1M2MXNLWlRNCmlkcUVIMkZvSTZwZUZObWxESFNz
            c0VzRHhra0d4RnFVNmxGTGNNTlhpQk0KLS0tIEh4OThVU1cwQVJFTm9ORDYvMXZL
            cTdrOTBTZUdPUkF2NWxMRFdHOWhLMXcKntK4DJlexxLmXpOm72Mscd2mV7ZWAWIQ
            LaZfMcB4keDCoInzgk5ACx+XbU2Hqsz24nH88CQZfTfZHye1KSbtuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T07:33:52Z"
    mac: ENC[AES256_GCM,data:ZrIaZz5mdoXAYmt4kwBscF6uxTL3HJ2cj8q0A9qSCzXQrZXbnM9Nbzbv164pDWfJxpZOYEl5DAnEYBdG00h8idy6uBVQ50v2A1k9iHyod7ZhLJ3pPR/Ea6ccoBJbGCcO0D4nHbcwRIL5TxEvkfLckyUTh41w63aKvr7ngDlB+Yg=,iv:xMflFdLCk9+Z4/itkIPa788zDQLrlN+hXxCIRHz2chI=,tag:0BsoFiQk4Z0R7SJ3Z9fyVw==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.12.1
