apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: david-user-info
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: david-user-info
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: k8s-security-david-user-info/username
    - secretKey: firstName
      remoteRef:
        key: k8s-security-david-user-info/firstName
    - secretKey: lastName
      remoteRef:
        key: k8s-security-david-user-info/lastName
    - secretKey: email
      remoteRef:
        key: k8s-security-david-user-info/email
    - secretKey: displayName
      remoteRef:
        key: k8s-security-david-user-info/displayName
