apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: david-user-info
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: david-user-info
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        username: '{{ index . "username" }}'
        firstName: '{{ index . "firstName" }}'
        lastName: '{{ index . "lastName" }}'
        email: '{{ index . "email" }}'
        displayName: '{{ index . "displayName" }}'
  dataFrom:
    - extract:
        key: k8s-security-david-user-info
