apiVersion: v1
kind: Secret
metadata:
    name: david-user-info
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:gcVY/MI=,iv:TTCG+sELceuajT6+W1q1iD1D4zNyPvcN/BVXmWA5DS0=,tag:3fYh5axDZsNfCFWpTkO5fA==,type:str]
    firstName: ENC[AES256_GCM,data:ykUnRtQ=,iv:cdLu5JAJLtkqjXyn3n/0BhNWFGpe4B07c77WmBY52bQ=,tag:fCihzoN4JvdDMk/sO71giQ==,type:str]
    lastName: ENC[AES256_GCM,data:2nqz,iv:EfmO6CzK6DFRsmxL7sj3hUk2V5OyyKRNmiE+s9Yk20I=,tag:EaFBMeIpLknwHhOeruT48g==,type:str]
    email: ENC[AES256_GCM,data:vHs8lmy6lx9Z+rzk,iv:nLVhm9EFV3oshEYFTCHnKRfr00kwhDfO3GDDxfBYDNc=,tag:p9IToKo4j8R3/PSG8fLiFg==,type:str]
    displayName: ENC[AES256_GCM,data:0i1q0kI+tGct,iv:Y44U0qt23nI2DSKhNvV6SACkd5gVLIX50758W9XCDws=,tag:ugtwYSfUYQmiQw73rb77GA==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eWdsS2FlaStSZ3FiMExm
            d240citwZ0x6dFNDVlBKUG5YT1M2MXNLWlRNCmlkcUVIMkZvSTZwZUZObWxESFNz
            c0VzRHhra0d4RnFVNmxGTGNNTlhpQk0KLS0tIEh4OThVU1cwQVJFTm9ORDYvMXZL
            cTdrOTBTZUdPUkF2NWxMRFdHOWhLMXcKntK4DJlexxLmXpOm72Mscd2mV7ZWAWIQ
            LaZfMcB4keDCoInzgk5ACx+XbU2Hqsz24nH88CQZfTfZHye1KSbtuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T00:12:12Z"
    mac: ENC[AES256_GCM,data:M6s3axLvW6MbeSwhFc33i1NNgk7MeZwWOiFjNyUTD/R3McP4rcG0QukhpmnnLdoD/DQoR2G8e5q3Sy1k8v/i9YthJVREZTjJxAu3p1wwf3p/duSy9yrRRmDZYa3hsn/C4HomVbt/quQC/Ed4j2VEJ3TLCmbxEO+N4zkldVX7MTo=,iv:6Ku5ldKKjF5SSnnR0EmmT2ux+rSwbr9tQmYnZSTfOdI=,tag:e4Tn6CRYWUFOEoN6zSTBZg==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.12.1
