apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: continuwuity-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: continuwuity-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: CONTINUWUITY_REGISTRATION_TOKEN
      remoteRef:
        key: k8s-social-continuwuity-secret/CONTINUWUITY_REGISTRATION_TOKEN
    - secretKey: CONTINUWUITY_TURN_SECRET
      remoteRef:
        key: k8s-social-continuwuity-secret/CONTINUWUITY_TURN_SECRET
