apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: continuwuity-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: continuwuity-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        CONTINUWUITY_REGISTRATION_TOKEN: '{{ index . "CONTINUWUITY_REGISTRATION_TOKEN" }}'
        CONTINUWUITY_TURN_SECRET: '{{ index . "CONTINUWUITY_TURN_SECRET" }}'
  dataFrom:
    - extract:
        key: k8s-social-continuwuity-secret
