apiVersion: v1
kind: Secret
metadata:
    name: continuwuity-secret
type: Opaque
stringData:
    CONTINUWUITY_REGISTRATION_TOKEN: ENC[AES256_GCM,data:jBIUdDEshiCXhKC846Wcg7LYB7WZaQiw73ceCbjsas2nxPQqeQIsWrhe7zdC4UyH86bVzicUGiVW+1SspI+tVQ==,iv:ZQcLjK2fdRe2EGAGkynpAYEhQ9iazmddnXT+dUBXoQw=,tag:wuy21ER8uq5K+LgrdHD5sQ==,type:str]
    CONTINUWUITY_EMERGENCY_PASSWORD: ENC[AES256_GCM,data:4Saiw6nyHLwxmKwwq7WxHB0Pn1ALK0oUHUVZLp6nxIcTe3Pq6unrHbSaChM4Fjts4xrKuPDGzYodnPA3WAxd8g==,iv:INLQU/2Zu2Ng8vBzEh2M+dmvSAMCF6uD9b25CDV2KvM=,tag:333S3r5jhFsO/8QB2YFrQg==,type:str]
    CONTINUWUITY_TURN_SECRET: ENC[AES256_GCM,data:FuxGko/9zWI9M9axYdqReUqHM2RElEC7Kg57olTde08k30lKxuF8iGaKICdp67ioXS2y+yubI2Io9KnFPKIT,iv:D6IPRMbOhtKDa6dgrDy2ip3LC2RlHPRjhPjrsX4mqGQ=,tag:Q5Dzh1EF1GUjrhcg6UJTCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYzZsZEdFaWFidDhkZlMr
            SmVLWGhvMGFlTGE4UEFqMGZTaHExZm4zQ1RBCnQ4SFprcUVmUnZXc01CTSsrRnJP
            UGVZSkVjelMxZUkzQWNjMTZFR0hLL3cKLS0tIHAyRlIvZXh2Z1RkemN4dk9xQTFN
            cGZXNzREQ2pWOFdTZGRndDlwOFBhbnMKO2ulL015kwXeWAgi5k0xoH6ATelgAXKg
            TDV0g5rY8NotRDjAlFMQZ0fiRbIzvnuCuc7b02fJKnHmna89mnhS9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-10T05:13:40Z"
    mac: ENC[AES256_GCM,data:3uu2baGfjdXLkO9UhFSNS9own6zQu5KJlSZ9YQr6gkvPfORMuNe3qBTj1sUdLSXjmzStOH4UA1QCxzX8eiGPiMgxt5fjlRb6V+y4FWEycPBecHsmsKBa41xt0QIqwB5KtzUHznds2MxUy2rqEk7qmsGwB6+I0npyQNDus6cGBqA=,iv:fDKFfaJnhsgScMQ5tlhxcBOodQ98r0y7FZPybPnMRds=,tag:kUdPLHkiWHLZMLiKmXpzBQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
