---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  conditions:
    - namespaceSelector:
        matchLabels:
          external-secrets.io/managed: "true"
  provider:
    onepasswordSDK:
      vault: homelab
      auth:
        serviceAccountSecretRef:
          name: onepassword-service-account-token
          namespace: external-secrets
          key: token
