---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets-source
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cluster-secrets-source
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: k8s-cluster-secrets/SECRET_DOMAIN
    - secretKey: CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: k8s-cluster-secrets/CLOUDFLARE_TUNNEL_ID
    - secretKey: GARAGE_ENDPOINT_URL
      remoteRef:
        key: k8s-cluster-secrets/GARAGE_ENDPOINT_URL
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cluster-secrets
spec:
  externalSecretName: cluster-secrets
  namespaceSelectors:
    - matchLabels:
        external-secrets.io/cluster-secrets: "true"
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 1h
    refreshPolicy: Periodic
    secretStoreRef:
      kind: ClusterSecretStore
      name: cluster-secrets-fanout
    target:
      name: cluster-secrets
      creationPolicy: Owner
      deletionPolicy: Retain
      template:
        type: Opaque
    data:
      - secretKey: SECRET_DOMAIN
        remoteRef:
          key: cluster-secrets-source
          property: SECRET_DOMAIN
      - secretKey: CLOUDFLARE_TUNNEL_ID
        remoteRef:
          key: cluster-secrets-source
          property: CLOUDFLARE_TUNNEL_ID
      - secretKey: GARAGE_ENDPOINT_URL
        remoteRef:
          key: cluster-secrets-source
          property: GARAGE_ENDPOINT_URL
