apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secret
type: Opaque
stringData:
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:2Xn3Hz+YijeahDFJ7cF+wZ0ifr2ncAWofLtv9o3NVvZSet/yR7wVCTfZWCD62mBH6iHjfakfSO+pOfApHImkVg==,iv:Unn/Rq8vWEPqs8u54VHRCrn20gjG0jbK9ZpvdqUT3Vc=,tag:BLBSrU5coObM8iKTJxl/pA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRnVxVHVPY2JiVDB6eDZr
        NHdONHU4OGV5RmR2cm9jczFUKzJqMXF1ZDBZClVDR2s3eFF4QVZDTXJEbXBUWWhp
        eDRES3pJb1BpL3NibFlGZU4rODF5T3cKLS0tIDZqSHBDWTZySzlxWWd0Y0hlOU9N
        dU5EMUdhNnFNTFFuYzAxTVVhYVFsWDQKMzvgx1QDrsudnTYtgh9zBd+J4Wq38Xm6
        dAB+VK0ScQlWtqoQlZXUOIXgRtkPQEohlesjFeXywyZ7Ul7/WbpbFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-16T02:14:07Z"
  mac: ENC[AES256_GCM,data:9W/PMFQPEG8qE4oSnbM7zyS6CmLkcScibmpC01PKrX/nWc2AjtG1xsG+m250zFN6+0I/LKoZN6A5Pf94BUGMkYyjeEuSmXFOZqA0JDPti4Sjfg3vUarKkdMS+57Pf4WbeRnGlcnU4VATBP2MRBNbZkOlSucnSc92dxSN9cNBiyA=,iv:ShfK2eWAFZaMNrqo+6ckEQWIZoCN0MaWFftWzyV1Few=,tag:a8S+JmXZp7TY8rE9YcxUWw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
