apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:nOtYUbxXMd6MWSwPExIHs+efSOEicQ==,iv:kUs6FElun+NdrDOnHf2B4RJ2ua7ZEerWQs7TnfgESyY=,tag:7RgmVsahcv/ETVgFOFSufA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:TxrR5m0GGCWNqbY0tg0XWHiGARXpzAFTnN0kOK9Fm1uzR4ctoAfwfJ6BFu/m/c/Na8PfAZ0otc2PBKvMK5pgjg==,iv:9ocdRhVs0lCL32vRHIOF1oLYD64/+C5S1t1Cx3bkS9A=,tag:R+MVci1wXFL0L4sfmgemGA==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtT0c4WG5HYXNIUEtqZWVZ
            TVRKcUx3dVpkRDRoZDdSeDJLM25DYmdmL1NFCmlFWHVqbjh4UFNtNzVja2tIanM4
            N2tDaG9TUlF2RFVNYWpYL3V1VnR0TDAKLS0tIEYzcGUzQmMyZytBVkpaY3pGWFBa
            Vk1KcVpXSjlEa3lwTWR6ZDA5Z0dKOVEKwkZ86OmcS5si4PGkwqEds3kT6BIXMJ+u
            gL9sph5Oduf/dNaq0jYJGaN3sPLeqBsznWgqkBAOStIfs+6V3f40JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T12:16:10Z"
    mac: ENC[AES256_GCM,data:q7idPRgjZXDjS9i2riY0xio0u6eLnvFyeXc4JAOTblgRF1zLpWUrCUqMwD3qrrOiT654Pj3zw5PX9m4IHAjio/LFFMfYAQ0p9JSoLs8NQyvR5sR1THj5VfbcEbaPTcE2k187b+/sPOhM3WeTJpZ2eyV2VS47ICWhI4qZo1kEPY4=,iv:KqMDnDotG4iBnOdNAItFd9skkYjyVJRE1b4qh9RJXCs=,tag:0ja/mSrzw1FFeQKURSo+Cw==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.12.2
