apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wCHsWUsWY+P2vhc=,iv:LoC4VlkIHJRVUJLN+jftzaeExjIkyYwBbT4ioMdJ+aU=,tag:xJV0YHqxo+QtejKK/T23mQ==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VSuEJJojtgQKq+33yCeD2puImzKgJY/oejfh9WNDPklAY4S3,iv:fSH+lXkRXDCSOancg4AfQGvKR0IYs/m75gXII1VIcv0=,tag:QmXgzRGNC1d/A0vhUgHwFg==,type:str]
    GARAGE_ENDPOINT_URL: ENC[AES256_GCM,data:WwNDrRuDGdbu2twUSs+OQ3BAwMpeLw==,iv:pcxlJvATAKVEPYqQcYcK7M6Fe/ymR2zrFBsbyBu+DDs=,tag:m+QFcRDZPNXsKG4rG4HSDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTXQrVWhrYm10b0grVHlm
            N0FxVDN3Ry9zZlYxKzJkclRXZ0xoVVZlWTNrCnBibERpeHEzTW4wMWJwR0Q4ckR5
            YWNSTzd2S3VCeHdkNWZXY2ZJT1I5bDAKLS0tIDhDdHJaNHhYVUlJWnp6c0xIUXAv
            ck15cnJhZjYzWTRZU1g3RzJhODlhdVEKqTuY2q5nOZh47ntzMIqpcEQz7pjQ3PPM
            W2Qle6Vt8OJpob9TRQ5f11l1vAkmKWEEYOpflglSlBR23L5lRgVU3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    lastmodified: "2026-06-04T06:15:28Z"
    mac: ENC[AES256_GCM,data:dy/d2OVUSyfuohuo4b3jgiCSlqPgoee4rLAAZoD1pW7k+PVz0/7JaPw05XhrFwv/gR68did3wwlU2lvpJNtjGiTr9B3th+DgUd59XOlBQgjl8xgSP4XEs14nMvQqNa+rFp6y/8RCbRttdbr3vDfThvfBLlhDj8ZX+WYG4Zk+BxU=,iv:YOaFYnw5SPoszarGq9LaQIAUhJZH7FVW3o1fpCS3P48=,tag:iK3K+b3b8X1riIT00L9sxQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
