k3s:
  vars:
    ansible_user: debian
    gateway: 192.168.40.1
    dns: 192.168.40.1
  children:
    servers:
    agents:

servers:
  vars:
    k3s_control_node: true
    k3s_server:
      disable:
        - local-storage
  hosts:
    vk0:
      ansible_host: 192.168.41.10
    k0:
      ansible_host: 192.168.40.10
    k1:
      ansible_host: 192.168.40.11

agents:
  hosts:
    k2:
      ansible_host: 192.168.40.12
      k3s_agent:
        node-label:
          - "coral-tpu.present=true"
    k3:
      ansible_host: 192.168.40.13
      k3s_agent:
        node-label:
          - "coral-tpu.present=true"
    k4:
      ansible_host: 192.168.40.14
      k3s_agent:
        node-label:
          - "coral-tpu.present=true"
    k5:
      ansible_host: 192.168.40.15
      k3s_agent:
        node-label:
          - "coral-tpu.present=true"
    k6:
      ansible_host: 192.168.40.16
    k7:
      ansible_host: 192.168.40.17

physical:
  hosts:
    k0:
    k1:
    k2:
    k3:
    k4:
    k5:
    k6:
    k7:

virtual:
  hosts:
    vk0:
