apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: konflate-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        KONFLATE_WEBHOOK_SECRET: '{{ index . "KONFLATE_WEBHOOK_SECRET" }}'
        KONFLATE_APP_CLIENT_ID: '{{ index . "KONFLATE_APP_CLIENT_ID" }}'
        KONFLATE_APP_PRIVATE_KEY: '{{ index . "KONFLATE_APP_PRIVATE_KEY" }}'
  dataFrom:
    - extract:
        key: k8s-flux-system-konflate-secret
