apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: konflate-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: KONFLATE_WEBHOOK_SECRET
      remoteRef:
        key: k8s-flux-system-konflate-secret/KONFLATE_WEBHOOK_SECRET
    - secretKey: KONFLATE_APP_CLIENT_ID
      remoteRef:
        key: k8s-flux-system-konflate-secret/KONFLATE_APP_CLIENT_ID
    - secretKey: KONFLATE_APP_PRIVATE_KEY
      remoteRef:
        key: k8s-flux-system-konflate-secret/KONFLATE_APP_PRIVATE_KEY
