apiVersion: v1
kind: Secret
metadata:
    name: konflate-secret
stringData:
    KONFLATE_TOKEN: ENC[AES256_GCM,data:LYKrcDhqrTqUUU4hnAMC9C/61S2AM4oiN6sJgnl0ZPsm7mvdXF7LPMUE6YkfSi87SpO8RPGuMuFYI/ayOr3JG2XVT3t3nPcsfKWgRx3aomkauhEYsVEhzUbo2Z8g,iv:yEVV1dptbWOp74UMN38Ksr1CUN6FgnJpNpHISV5h2PM=,tag:AlTx9xV8DzGbZ6PONUfVIA==,type:str]
    KONFLATE_WEBHOOK_SECRET: ENC[AES256_GCM,data:yZGFkI2jby+OawXgWdlenRDaaOcWKpMUC4RlRg3ATWOdJS0yiV2s8BrWF9PnhpHk+s8+Yveglr+ZUN35FsVFsQ==,iv:c11OxrX+sZB+249WXkY5lS3l4Z3jPQFVlSKgN8mqfZs=,tag:V3uU6sE2IH+D93sE6oDI8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R3pwd280TXNaNFlKLzhy
            eFFFeVM3MTVtS1NrbEQ3MDQ2MEdKS2dCeTBZCmhuMlZQSkpzeHdJaEs0d1FsZmx6
            bHZhcjJWUGEybFF2Y0IzRnBkV0lDaG8KLS0tIFpoWVM2NHdLQVNBUEY3YWlVWktI
            TEs4ZjMzUnVEdUNDWmFyeWQrYnNhM28KDKeFSlOzZtlrDseYPqGNs8/fr9SWwK3b
            TZ/pDwstGA8xAvEqcfil4Q5g+Gs9NDQkYxDT5Op9MA5x6lWPJKozig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T00:37:44Z"
    mac: ENC[AES256_GCM,data:Rg1/gZ42zfTgOqOEOm/N1/22cwfac0DU+63ojWcOtzyDxqDWMTonEvg+baKLdxcRswAidMY3BO1koM7JpQdFCEtb7QnQln74GLcnT3j8hlKUiUxfHWm6L+VvMiFCuH23gnG13KAZvTir8n2swWsk36q5vaYptLNQH4Q+Ll9aE7M=,iv:k9u5dekTNvmEozqTpJbvgz5zUzGOz9g+bUQb+ZH4hGI=,tag:KvePrkdpbyjrOyOEZP1SwQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
