apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
type: Opaque
stringData: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOTQwMEFDRW94Q09rbTJ6
            OXZONERaQ0wxdWdCdFEvT3VKelM3V1QxcEVNCkh4eFNadnhnekxtODU5UUQyN2ps
            bHNmaVVqeGRFMG9OYWNSVjNQU2FzTGcKLS0tIE55RkozUy9JeG81WGV6R1pNZHEr
            aUdUMXNleFZuaHVYM1hqRlc5ZnRId1EKIXOs5CsY8d+FajvY+8F3e1V7jJWqL7QG
            +YUk+L7XXWm4q2vw301OeVDuc3vLglZuKlK2/X1dZEvgPi6Znlpktw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-20T05:40:52Z"
    mac: ENC[AES256_GCM,data:lCDCSHEm5x3Jbs39PTs3OQUAQNGzNqSPTt7gIUuqUwM86Q57DoglZSfM59RNrmsJ3uwkxbOljsJrhVWxK95a5O7b2dtUS+TSXOyFSo2gQAYlGoUJ0tA6laKjRzYzwSDYUoIQs/Y4WydWkZMNT2zyptryfE+vEwwUreqtu1S1Guc=,iv:/B2MbBJgfItubgFMiK0KajtXw5LerAkMWMhF1WMi0v4=,tag:JifyTEP/I61hjZgjrv9qGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
