apiVersion: v1
kind: Secret
metadata:
    name: paperless-postgres-secrets
    namespace: flux-system
type: Opaque
stringData:
    POSTGRES_USERNAME: ENC[AES256_GCM,data:NV88cmzq4nKo,iv:CGX8e/31OTBmrIefU3nE2eFngbdIaU0rTiwgP8AZK+Y=,tag:pkl1pBBdddM07ZZpcpuEog==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:B8jfbQ9r4O1q8VFaI40+KvVnc5Od4JT/,iv:upgTD6rw2SRYHnOzBQsYv6lBxh/mDHiPrlstl7/ujuE=,tag:OqUOiB1gZrbnNRdJYvJl6Q==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:4GLrs7dsfLIe,iv:NDuOxq8u8cgy2VAQebJD76DTb0cohqPiZZR4tIIcG1Q=,tag:qi9cgQEhjv1iIiIvML63hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOTQwMEFDRW94Q09rbTJ6
            OXZONERaQ0wxdWdCdFEvT3VKelM3V1QxcEVNCkh4eFNadnhnekxtODU5UUQyN2ps
            bHNmaVVqeGRFMG9OYWNSVjNQU2FzTGcKLS0tIE55RkozUy9JeG81WGV6R1pNZHEr
            aUdUMXNleFZuaHVYM1hqRlc5ZnRId1EKIXOs5CsY8d+FajvY+8F3e1V7jJWqL7QG
            +YUk+L7XXWm4q2vw301OeVDuc3vLglZuKlK2/X1dZEvgPi6Znlpktw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T02:54:40Z"
    mac: ENC[AES256_GCM,data:KWD8dr1cjF2EzFZEns/pXQ3wrVmTILhbPYHMl/Vxbjv+U2ksKPL6iEqHzgjvWH49CJ2e3DWN7RMtYdRrwmvUyuzjsvN4onmut+5DC1Ldwx4l61L8SUjxI0KAiq7/tIdRcHJsYHm9tz5oxQe8Ly+LN9u4Tty3uigR3wWlHGDjY0k=,iv:Ss71DLty6EFu/cxSuuTqT1HpXdwDxi9yvp9asHp15zc=,tag:Xs1nYXJsbKdWMHfUrjJQCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
