apiVersion: v1
kind: Secret
metadata:
    name: paperless-redis-secrets
    namespace: default
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:+EV9ywnkBksUVnaOLKyaoA4cXxOZqTuv,iv:eCpKLuGX4jjM3bzw5dGRHiMGIhYRc8bdaWI50pngsV4=,tag:gwysqA0aQ1GXlPs/4dtjWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdkI1OTZkdldoMHhMMHl4
            TFR5Rkg4U3YvenVVZHZFVVV0S1d3Vlh3VVEwCnZ0dWdZVjBYdmJRSElrTzNiSHFM
            b3Qra0thOHJtc0FYeDdJM1B1bERHczgKLS0tIDNEUDJKdUw4MWVoUm9LK1pMUXVP
            aXpZZmYxOEhzWTBNSENtT0JMOTdsZXMKw++zw8dTKMfd9VTW8KryrmPNg5is997F
            2q6os7jq8Gi9Mg8D5SyHezTsDRpwzlGtccf9j/UoNjP6acEMCI8M3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T03:06:48Z"
    mac: ENC[AES256_GCM,data:73/ArPRt6q8IGFsCSiz+A7F5uxahnY4mrl5NHsSnV63U5e5AUwJ1Ca8BX7p72o5keBOyGw3WYLiaDuNNlTpxxS/HAXJSnTLVFinWEtddHOm+KP4Ir6r1h0L4PIlWQZXkrc8paZ3eGb/vBhxCLRODaEM6A9DBUC7ynJeJDSDOK0Y=,iv:4HEUBgnJkcIk6hK40hP0OtnLKbJuTerByym2TpDmOoc=,tag:1EUEW37Cn2em7WKl64aqxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
