apiVersion: v1
kind: Secret
metadata:
    name: paperless-redis-secrets
    namespace: flux-system
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:+EV9ywnkBksUVnaOLKyaoA4cXxOZqTuv,iv:eCpKLuGX4jjM3bzw5dGRHiMGIhYRc8bdaWI50pngsV4=,tag:gwysqA0aQ1GXlPs/4dtjWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdkI1OTZkdldoMHhMMHl4
            TFR5Rkg4U3YvenVVZHZFVVV0S1d3Vlh3VVEwCnZ0dWdZVjBYdmJRSElrTzNiSHFM
            b3Qra0thOHJtc0FYeDdJM1B1bERHczgKLS0tIDNEUDJKdUw4MWVoUm9LK1pMUXVP
            aXpZZmYxOEhzWTBNSENtT0JMOTdsZXMKw++zw8dTKMfd9VTW8KryrmPNg5is997F
            2q6os7jq8Gi9Mg8D5SyHezTsDRpwzlGtccf9j/UoNjP6acEMCI8M3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T02:53:14Z"
    mac: ENC[AES256_GCM,data:EWO+SRo0ZmidMlLFOGOqyZeztF9icpWrcga11HF7Wc2NvdYh7ywKD02v6geHidGFRfkOaRPDYe6bZIyiKSqK2nEgI9d4cZVc/mcMqoTOZTV3jW42U0GvtPoogZHKzrxpHnZkKMoY3gO29h4qTg8aeDsCT5i0h84SUpUEGbyCVHg=,iv:SUHU4R6HqS8qGiU4hTjaBYdfdiYpSZQrlJxdBSHqZts=,tag:4CHVBFMKpWHlw7dTH0AYaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
