apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin-postgres-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: atuin-postgres-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "database"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      mergePolicy: Replace
      data:
        username: '{{ index . "username" }}'
        password: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: k8s-tools-atuin-postgres-secret
