---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: &app atuin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/service: *app
  endpoints:
    - port: metrics
