apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-token-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-webhook-token-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: token
      remoteRef:
        key: k8s-flux-system-github-webhook-token-secret/token
