---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sabnzbd
spec:
  dependsOn:
    - name: pocket-id
      namespace: security
    - name: kopiur-repository
      namespace: kopiur-system
  components:
    - ../../../../components/oidc/envoy
    - ../../../../components/kopiur
  interval: 1h
  path: ./kubernetes/apps/media/sabnzbd/app
  postBuild:
    substitute:
      APP: *app
      APP_ICON_URL: "https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/sabnzbd.svg"
      OIDC_APP_NAME: SABnzbd
      KOPIUR_CAPACITY: 5Gi
      KOPIUR_UID: "4008"
      KOPIUR_GID: "4008"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
