---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator
spec:
  components:
    - ../../../../components/oidc
  interval: 1h
  path: ./kubernetes/apps/flux-system/flux-operator/app
  postBuild:
    substitute:
      APP: flux-operator
      SUBDOMAIN: flux
      APP_ICON_URL: "https://raw.githubusercontent.com/fluxcd/website/refs/heads/main/assets/icons/logo.svg"
      OIDC_APP_NAME: Flux Operator
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: flux-operator-oidc-credentials
        kind: Secret
        optional: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: flux-system
  wait: true
