apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: VPN_SERVICE_PROVIDER
      remoteRef:
        key: k8s-media-qbittorrent-secret/VPN_SERVICE_PROVIDER
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: k8s-media-qbittorrent-secret/WIREGUARD_PRIVATE_KEY
    - secretKey: SERVER_COUNTRIES
      remoteRef:
        key: k8s-media-qbittorrent-secret/SERVER_COUNTRIES
