apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
type: Opaque
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:gQiBT/C2syVa,iv:sUzN7vUDT3nTRK+P71wC+uw7Il6xqI+QWN7h52UW8vU=,tag:oQLlo4aRZHYrd10R0ezyWA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:Z+gcCdUME9PsAzSNcX8qWoeU5xwvvjGkQEXeKRxgO3mLzUYgRG5b69Ec/sA=,iv:Sbl1O+/rX2mX3sXE6/BxkEUCErq/Mq2cbfjoQWpIgmM=,tag:3NbH8Dioak0clu+NyaxqNw==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:AfL9hDDBMh8Q/2afz4s/4cdcZOKzMBrXWjc=,iv:l6TUIrNAdo0fD97vVa1RE+9wYQPzRJ8qu2QmFwFgdwE=,tag:IivWBMQJFtXlRbXqIwlLVA==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaWF5OThKK25FZVhCWmhF
            SDNPdElqek9qQXRTWDZQQU45czBDcGptZUU4CnNkNU5zVy9uT3FIZDhST1hDZnA0
            L2tWaEtyNVYzbGNhVnZGNkJhanQ1bHMKLS0tIDBSazVEVy9FTWlybi9HNlhLZmtF
            YkVEY3diV05uVUE2Y0xtRGRjbGMwNlUKdKZTeHUm++ibVZsU+RGLAmP+DhwyKZ9o
            XmzhrCrhlc6xNiOZSfMKfNrK47mH1PXxF5Kcw4mM7H8Nq/kHQ/TfJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T05:58:44Z"
    mac: ENC[AES256_GCM,data:taNsgbeOTeWnzEKlcBo7JLCut856xLMbo5Sds3Dc5Gdfcq9kdw67bwWigMZxngL1ptGtWnPM9i6y3Wa9kAm1qkJXz6nOA7pfqMItBw8NhuDabM/vv0IQhyDGa5zfNO8ezrMvw8d06MlQuMVM+0BXXTobZEAt5rki+WtKKGHD/5s=,iv:Uf2akEyROewliQWj8Mkd/OeqcUr5iQy+vapmTxob9YE=,tag:QX1X/dsVbavnsKQF0QClEA==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.12.1
