apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:bcNxKJbFrqN2B5WLUCqLTfPXe7vr+vHI9Te1c+vxMfJOFBu8Io1dBXQwRxLetAG3PFkIOGppYS1s2XvkG/WbxeOHUuokTNQ+sO/SozSzEDrZfZJ4lCqubPdlhgdJkpaV8hlBSFC+dZkzHexn3W9+dxzzAD3sYaK3EyEtrvDpd4+0zeVKjnmZBl5bMiTiDRHf3VcoYd9K4giacH5dmUeWNGz0WroETannu9eYyouZnxRGZUFpIXFs6fxLDMfYYX4Fh+00yBjFl9WBIQvfBwD/j5/U4tzdmK1aBf7upyIY9xbgkZsH3ne4Kqi7Pvp6r+ejP979TOelUunekUeiK3oBsbKb2cNt0iPraMqcWWbukwGlNgE/AgbpVU5WZ72FxbIFmzY4kyj8GI15dj3Kd4e1YtLTxLUwX6GdBQ02yGkkKgZt4MRYaaOiM6uVVHSn9k0+uzROtj6J9xnPeEHF4iIxLHIcSPjicyL3hfiMwpwPQpaj0k8NIyeyxNZqALT/bUI3+Bc6mawLpU5f9S+Eqh+e,iv:N/YJj+B2ygAgNc9MgbzJf2rGs+a9YhQEKT43vZjHk2Y=,tag:zCiEyInpbOfw4sdxoMlb5g==,type:str]
    identity.pub: ENC[AES256_GCM,data:CVT/Ax4ELp1jzZppwvn9GAbBCgTe0ridoUXGmgsrT4ZjDijEdKsSeI1KWzfppp/pECrluAo/gIxCN/vv5yhpE6GZdTSU/2DWVXLp8v+mkUGPi7ghScFmZunktpw=,iv:fujLpncVyHYHMC9cMv6+X9GQYIJi7TjV1krG9eqLvqc=,tag:/vRzogC/n+aLb2tYqM1hjQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:uOrIWhteaJwPNxIw6Q/KZXHG/cSfFf1kGi8UrxCoIq9Iri4YHiUt2Rjv/RR//TzkfAG2DYCKEWPtRjr2aCalxnrks7Qzy/d8qU8OyjhIKhiGo01tB5Bz502S1ROiZRKuFDFQXYDDA29nmFN4tkwV8PqzX4r7edCbNEuQvayUXDGG/D8JTXNvnzNntBeWqWEUPQHawz2TPbTadSb7pzGj7TttP4V6uCNrW1Uw,iv:YNaLeQWUd4azdV8B4RgYTTnHNkPzHSsw6pAiZFy8k3w=,tag:I2bHSQSXbFjYvvegkqT0Cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcHN4THFBRDc3SUJGSlFR
            L1Q1YTdUL0trblg3RzFaZ1pFU3FZTG1VZ3pNClQ1US9vVXRaa2Y4QXVUZzhoaGNk
            VWNnNmkvVXkrWkVka3F5Y2YxaDliOEEKLS0tIFN5K3dkOHNnVUdMSzNSWDUrV2FC
            bGE3Z1hsVm9SVzlQTXFSQmtMdXl1Q2sKFXvKcaagnxArTdWbFd7h33z5fV/utsjs
            1XpOX1U76OYh2Q9Y+u5oarhodnCtCtN3uy1qJcpomQwcgKsd96mNxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T05:43:28Z"
    mac: ENC[AES256_GCM,data:9bjzyR6g1+Dp2yCz+mE7K0NlIbecGFqi5+OTFztFgnp+CL22Ubs9BUxXO6RkKU6nFt1kAiaUTdqsj98stZyuKtuZdtfiHoCBievGFimbkUQEYjd3hFq68eI+wJn/f0XoCkETY4JpmZQwgiHXa0Lo5KGGEQ2yboBKlzHzOQY3hyQ=,iv:KZiS4Jmy0A6z/5Rt1WadhqaWh2k+cF/bFeiItAOp054=,tag:ilXR+y8lbJy2uVFwZAR7Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
