---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: towonel-agent
spec:
  endpoints:
    - dnsName: "towonel.${SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["edge-na.towonel.dev"]
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
