apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: towonel-agent-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: towonel-agent-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: TOWONEL_INVITE_TOKEN
      remoteRef:
        key: k8s-network-towonel-agent-secret/TOWONEL_INVITE_TOKEN
