apiVersion: v1
kind: Secret
metadata:
  name: towonel-agent-secret
stringData:
  TOWONEL_INVITE_TOKEN: ENC[AES256_GCM,data:rm3ZUa/9/5i84y/TkPjvg0zBpZ+oEzo69ht+ZxIG33V79nMUy1uvYvXrvhQu9SFPyYRLxvHz3VByt1hCcuLwFAiehHTh41p+Xao4ReJGdwBwfeVvId68bA1xwbbtDNL8okYXpElaVWIvCUjdc2mZiwVQVYKI8GdXoi+AntSV65ShRSA7ZOMkOG3nYAIC4aNziZmHZvhQqw==,iv:XlzVCLkyT3WN9N8MQW/If/zuLJVdLyjYpqinoJ4iiVY=,tag:m0J5fTIJ6jUMBUDald7vfQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdTVvQzdBU1ZNN1FVWVJT
        cXM3QTBaUUR3bVBKbzE3ekJCbDFPVXRKd0ZvCmVINW5LaE05ZHhFazBxMnh1TkVX
        OE1qa0ZZVENDbE1JU3l0bU0ySU5NRGcKLS0tIFZvVUpYcVVhb3JIVGIrZXBBU1Vi
        VXl5bTFTemNTOFFVT2dXdlBwTGVYeGcK0XAxNMOiBkhJRHtp+6VLIJxeNO+xaE+6
        PCEXKuOgLdmW1ZNAN2wTYVRHRVAcXt0KrgCIIEqTN5Yw/b50mkFGZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-09T02:50:37Z"
  mac: ENC[AES256_GCM,data:VO5oaWoKlDePmvCl81gSqoMrjh0/AsF/Pfk4pFnOlwZe2Waqq3Rqcf01ZZXWjXWXu9YAB2mO0eBeVya38nU8i6aLnbmDjQEvDxbTyeWpxyNa8AWHueNmkdLPeeGQ6SI2WUGAPsCdb9h7TSlXYNr8SmNxL9fqlUelQVLr0t1c7IY=,iv:SQo27MsxeUzFdB8M24LjvhFVn9uIsf7x9f1iUDJrPxw=,tag:Eu6784sAv4s4am6WLQE3cQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
