apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: sonarr-postgres-secret
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: database
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    username: ENC[AES256_GCM,data:CMkO47Bw,iv:w+KAyeZfq8YF10c317+xuZOerqcg72fiNMH7rmwMnkQ=,tag:qRrfcEzxunt4l0U7ZIOEtQ==,type:str]
    password: ENC[AES256_GCM,data:UcJcptcAgDobt8ymbjEB0muRPd/Fj4r9SGRwWphBFuHhBECwlTjnOUui9hNXRzB4AqR2HX9zjfopc2zv12DV4g==,iv:TWN9hei0fjCFJJQF6ELGgkC1hXxnflraZbQgWFkPT/U=,tag:C+ebWFfWPGgs8VNGoHBxtg==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaDdUbW5vTGMvY0dUYUk2
            K2VtMlFIWG5FQmVxdE1jb2lrbWNLZmVOQUdrCnU2YmhZaTh3OElNeFlVR0hyd3Jo
            aVc5d2hjUDN2dFM1Vk1mMWdyeTlJK1EKLS0tIFJscHJUUS83MkVFWUM1dE1YY3lU
            Ukt0dVFLbHJHNmJhTUVSdXNSeDRERUkKV1MCD+6+yVT2BcpZXWcaixFFkwZbm6uv
            HMsaqDW4IBhV+ZVXOW38kv4VW9Ct3Dy3dfph0i71/PT96FAKiuD0eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T04:23:12Z"
    mac: ENC[AES256_GCM,data:j7ADXyZej9p9/PaPfHpMICPo0E8P2Uv8hYb9A5JHv/mHp7pYeK5XN03yJFMYeVf+JjJYCAl3JU9I+aWpRgJYvgLPttfNbmEzSzHZWZjwIcg9wMAFYrrxyouk1IeiM76/b3tNtWGXf2Ewk8+wBVBVr3b8KpL5GC2us1kKDz+cftw=,iv:Rgf9MM3jVJggnhFT2KmZnZv5goSJSHIk01TjO/EkkTQ=,tag:gAJPERKzXHr0ZRLghwxShQ==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:F7pqRGnFe75Ay3wLw0PF2vBOzoV0IFqTrnPjy0V/p+aKVWk/HBaHMaIExofdnlfAVDQ9ovJZ0X3U5coavPJY5g==,iv:iU+BOhkSBuoQH1blSH9Wtp3lX9II/Q/gPWnYbjEEPEs=,tag:PivDkUO402lRAgflIBLsYw==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaDdUbW5vTGMvY0dUYUk2
            K2VtMlFIWG5FQmVxdE1jb2lrbWNLZmVOQUdrCnU2YmhZaTh3OElNeFlVR0hyd3Jo
            aVc5d2hjUDN2dFM1Vk1mMWdyeTlJK1EKLS0tIFJscHJUUS83MkVFWUM1dE1YY3lU
            Ukt0dVFLbHJHNmJhTUVSdXNSeDRERUkKV1MCD+6+yVT2BcpZXWcaixFFkwZbm6uv
            HMsaqDW4IBhV+ZVXOW38kv4VW9Ct3Dy3dfph0i71/PT96FAKiuD0eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T04:23:12Z"
    mac: ENC[AES256_GCM,data:j7ADXyZej9p9/PaPfHpMICPo0E8P2Uv8hYb9A5JHv/mHp7pYeK5XN03yJFMYeVf+JjJYCAl3JU9I+aWpRgJYvgLPttfNbmEzSzHZWZjwIcg9wMAFYrrxyouk1IeiM76/b3tNtWGXf2Ewk8+wBVBVr3b8KpL5GC2us1kKDz+cftw=,iv:Rgf9MM3jVJggnhFT2KmZnZv5goSJSHIk01TjO/EkkTQ=,tag:gAJPERKzXHr0ZRLghwxShQ==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.12.1
