---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app orcaslicer
spec:
  dependsOn:
    - name: kopiur-repository
      namespace: kopiur-system
    - name: intel-gpu-resource-driver
      namespace: kube-system
  components:
    - ../../../../components/oidc/envoy
    - ../../../../components/kopiur
  interval: 1h
  path: ./kubernetes/apps/maker/orcaslicer/app
  postBuild:
    substitute:
      APP: *app
      APP_ICON_URL: "https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/orca-slicer.svg"
      OIDC_APP_NAME: OrcaSlicer
      KOPIUR_CAPACITY: 5Gi
      KOPIUR_UID: "911"
      KOPIUR_GID: "911"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: maker
  wait: false
