apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memini-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: memini-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        MEMINI_API_KEY: '{{ index . "MEMINI_API_KEY" }}'
  dataFrom:
    - extract:
        key: k8s-ai-memini-secret
