apiVersion: v1
kind: Secret
metadata:
    name: memini-secret
type: Opaque
stringData:
    MEMINI_API_KEY: ENC[AES256_GCM,data:okB4DtwnYUXCdWfLNanHCjCnAP8M3zKcosS1Vn+bIXyuK09vu+uxVntaLkm/VaTu804uycLdDzkxZuJoeuExwg==,iv:jUtbdx1LK/qDzcGb2aieTAxhDP1wak/nbS6A5+/J1xU=,tag:DXy1WZ9yTScutCIUdL+Pkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdTlnTXgxQXVQbldMK3dN
            a0ZrcjlUV0NIdnNZRUwxNmkwaFpNR3RxQXdFClhjQ1B3TzZWNjhvQklsaDN3eTNU
            ZytpNmRjSWczSG5kKzI3U1ZxMmMvalUKLS0tIENiK09KNUVTbGEwekpnVWphRGZT
            THd6SXBEUGwxdisvbVdQYWFINWFuYTAKA2NwfI88VQqaBHKSbygU464r2YIzOXK5
            0NljaT+S/QlvLESS0PDvDIYHncMwDqHaC7y1HMJbW2Mf257COy6wHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T00:59:12Z"
    mac: ENC[AES256_GCM,data:mQ6BkeBnXFGM3fiLKNSnJwZU8E26+OFzhHwsxCM7faVh6690AIcRO+yK3XX0tGzR94OqIR7itl2+tPIscOW5S/2fpTJugC79V8Yq2Tu7GKWGwJxSVIXlKu48ZhzQVxquqfG65MuFDPrLtwVJEXPvpvaNV41qSGYJ/Nu3sv6gXuo=,iv:O9ijOV+dPGpmA/HJ6W9NPAwPNiOIkBXCtZxq0YBtuM4=,tag:RT3jaYmUpIMYYmxhECa96g==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
