# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  instances: 3
  # immich only officially supports PG 14,15,16 and pgvecto.rs >=0.2.0, <0.4.0
  # plans to move to vectorchord in the future
  # see: https://immich.app/docs/administration/postgres-standalone/#prerequisites
  # see: https://github.com/immich-app/immich/discussions/14280#discussioncomment-11726072
  # todo: figure out how to get renovate to track this
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.4.1@sha256:ed5ff8a789eaa88d1bde2e879a75dd02c104bc4f7a18c341848dde673db90d13

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  storage:
    size: 8Gi
    storageClass: local-hostpath

  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: true
  
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitSQL:
        # Immich expects its user to have superuser privileges
        # https://immich.app/docs/administration/postgres-standalone/#with-superuser-permission
        - ALTER USER immich WITH SUPERUSER;
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;

  backup:
    barmanObjectStore:
      destinationPath: "s3://potatobread-homelab-backup/cnpg/immich"
      endpointURL: https://s3.us-west-000.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-immich-backup
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-immich-backup
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: bzip2
      data:
        compression: bzip2