---
# yaml-language-server: $schema=https://github.com/aclerici38/pocket-id-operator/releases/latest/download/helmrelease_v2_pocket-id-operator.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id-operator
spec:
  chartRef:
    kind: OCIRepository
    name: pocket-id-operator
  interval: 1h
  values:
    instance:
      enabled: false
      spec:
        encryptionKey: {}
    metrics:
      enable: true
    prometheus:
      enable: true
