# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:yaW+Cf4XKi6x4aOjsPFN5AsNMp3J29YXFTNvxNwfAu21GrqX1W02Jw==,iv:SBQUPQUZXKqmvt4YrxqhAhtiYMHTQf7uSPTZ8lTh0ug=,tag:DnKKG2OzApnwRSBHSPwNEw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hkggfdsuse44s5aw3wulvq45h9u93lgvgarm8leqxnesf6knyffsgnh78f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWU9SR2g0OWF5MmR1bmo3
        U1JLVWZ6bmpIYXFCWkl3TUNYczE1MG1CbFcwCmwzTFM5dmdRa05qZ3B1bHh6dmF1
        b2xIYWsxZ3hXaGZ3UmVXNS8ybHRJZnMKLS0tIEx2M1RmUGp0azlqcmUvMzU5YWg3
        UjY1ZVlxL3NOMkdrQUFBajJJSmVETncK97qY4b1yX3PXGtfquXJbJORMnuTZTRee
        d6oIERqBKMvnCj4BbJruYel0blYZDHgvZHDr55couMSF6jsYCiVKjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-25T22:00:10Z"
  mac: ENC[AES256_GCM,data:NaZb9T1TF11hQkcCm21q3xJYyskPvgLEvnXAdAmxHYZ1uVnNLunNEh1/6aGro7Vg7rPNTXF+Gd++81N3qDUFJsxvMPnfRQ2cEXmFRfhmK9O6McH3ohN0T2dNEI/lnqDoMdb6hO2vjgWNv08bjoxVZta5uOkkGHStlWjSuKa9Qns=,iv:51eP6zKP6qQf0ZbYCmMJFaAPYWoZ30lawpdtQbVjV/0=,tag:MwMFKO0m7+LW+LWOqtzhog==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
