---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ingest
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      app:
        type: deployment
        containers:
          app:
            image:
              repository: ghcr.io/dockur/samba
              tag: 4.21.4@sha256:0f17c1703684f53850f40b9a84fa1897501ac26c6b60825574db50185a1a1793
            env:
              NAME: "paperless-ingest"
              USER: paperless
              PASS: paperless # idc, really
    service:
      app:
        controller: app
        ports:
          smb:
            port: 445
            protocol: TCP
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: paperless-ingest.${SECRET_DOMAIN}
    persistence:
      app:
        type: persistentVolumeClaim
        existingClaim: paperless-ingest
        globalMounts:
          - path: /storage