---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nvidia-gpu-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 26.3.2
    digest: sha256:629f943939e5bbf0115f5a962b04ad1c4336da179723687d6cf64d7fce203b01
  url: oci://ghcr.io/home-operations/charts-mirror/nvidia-gpu-operator
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/home-operations/charts-mirror.*$"
