---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nvidia-gpu-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 26.3.3
    digest: sha256:799a6e7b9162332ce1693b22a7d31365cbf567ff22ab0d8f72e4652dcd604e6c
  url: oci://ghcr.io/home-operations/charts-mirror/nvidia-gpu-operator
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/home-operations/charts-mirror.*$"
