---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tuppr
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    # todo: multi-node
    replicaCount: 1
    monitoring:
      serviceMonitor:
        enabled: true
