apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: prowlarr-postgres-secret
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: database
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    username: ENC[AES256_GCM,data:wUrVXGW4jPA=,iv:x62F4qrIhkprbIPwPzkj10S5FRxo3yL2oWSprqw5INQ=,tag:03BlNlQF0QHHFJynHJpn1g==,type:str]
    password: ENC[AES256_GCM,data:fQ/1amaGuppJmXy6JHnCSF6tjXyMLHB+kssFvwdTFb4hIExl/j5tecwUoCdqBk02G7At67r7VBmhifDpihspVQ==,iv:xtw/PpJT+VagmsmlCEz8KOsvdSU/XR8gA4WLunUhjcQ=,tag:HtX8lv5TJ35kPRmDE5mkig==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSEdXc2dhT1pydGQ2Z1Vu
            TlZJSnZPMEhrNnNEcE03dDgyMVVwMytMcDBNCnZEdmE5cGEyZnFFZllqc1pENUVK
            SEFNL0NmSGlLTElOYmk3cVlaM3VUbjAKLS0tIGhXQkJOUXo2dHBLbUczRll4V2gr
            Z25jNU40N0FuMStJdFpDb3ZOVytRRXMKFPAOR9TTrkNlNuuIudCKTKGB1LB/YJvp
            88bOXuxbfaeNsqAKhBQGpx0P4RPQHNk5ot8SvfGREhLR+ZRKJOnwDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T00:05:14Z"
    mac: ENC[AES256_GCM,data:MVEpAATJTfG31/6xiOnvsd7YU+UBFJA+3f2aCTJ0qt6s13beZOXvp5jjPn1PEyNGmBVuEkWKmnxch9z/1bLlsCa/jyjRorpWXXg3RFSkFv8+1CoKl1brcOP8PmfqWBe+4cNWW4kSABKpuHpO4K8XV3Qn3kkHfxEFIwQCohS8FaE=,iv:zu8wtj2hipGuBEdg6389fWwHUvIXkwr13PfyriPupys=,tag:6cfoykZVJCF+mr4yQmGG9w==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:nz9HXOK8IVHWoXsw0WQI0UZtCH223T1d7FbKmo0iu3PBOqHo5Ti5TQKj9xJNQj04eElTIxLrb828MUBCjLeRqg==,iv:fD2lc4Lt5IYsYb78Hyhwx9dkSXBfZvjldzuJAT0uSl0=,tag:6YE8jojGdR/DnkgD+7cD4Q==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSEdXc2dhT1pydGQ2Z1Vu
            TlZJSnZPMEhrNnNEcE03dDgyMVVwMytMcDBNCnZEdmE5cGEyZnFFZllqc1pENUVK
            SEFNL0NmSGlLTElOYmk3cVlaM3VUbjAKLS0tIGhXQkJOUXo2dHBLbUczRll4V2gr
            Z25jNU40N0FuMStJdFpDb3ZOVytRRXMKFPAOR9TTrkNlNuuIudCKTKGB1LB/YJvp
            88bOXuxbfaeNsqAKhBQGpx0P4RPQHNk5ot8SvfGREhLR+ZRKJOnwDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T00:05:14Z"
    mac: ENC[AES256_GCM,data:MVEpAATJTfG31/6xiOnvsd7YU+UBFJA+3f2aCTJ0qt6s13beZOXvp5jjPn1PEyNGmBVuEkWKmnxch9z/1bLlsCa/jyjRorpWXXg3RFSkFv8+1CoKl1brcOP8PmfqWBe+4cNWW4kSABKpuHpO4K8XV3Qn3kkHfxEFIwQCohS8FaE=,iv:zu8wtj2hipGuBEdg6389fWwHUvIXkwr13PfyriPupys=,tag:6cfoykZVJCF+mr4yQmGG9w==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.12.1
