---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-postgres
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: 16.4.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    auth:
      username: paperless
      database: paperless
      existingSecret: paperless-postgres-secret
    primary:
      persistence:
        enabled: true
