apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-postgres
spec:
  instances: 3

  storage:
    size: 8Gi
    storageClass: local-hostpath
  
  bootstrap:
    initdb:
      database: paperless
      owner: paperless