apiVersion: v1
kind: Secret
metadata:
    name: cnpg-paperless-backup
    labels:
        cnpg.io/reload: ""
type: Opaque
stringData:
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TFH5sXL8yYnrnpqQTDX6Bk6m6JpT48AoKbVHGIEdwQ==,iv:BpOSnkCeB1N5gZhH1fVFdnqw7eZ666EyA0RtQ8VkDJM=,tag:ufryWlYFJAkNWBnIvEMo5g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KQEEBCc+XLanl5ScfImovjBOu7za3cLMOA==,iv:e9yOElo0m7tODT+PDa9yIrnfsDskyaRXroF76F3N7M0=,tag:cA+VOlMx6KzBUzxpJdSELA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hkggfdsuse44s5aw3wulvq45h9u93lgvgarm8leqxnesf6knyffsgnh78f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNlRCK3dHRXNUcTgvVzFP
            d1NJR1dlVTQ1VnpIMFNwMVVSZmt5QnpmNlNFCmM1b1hMbmppemMraWgwUWVqMito
            QUloOUdUUDhJUjhnR2hwSTFRbm95cnMKLS0tIGlhS3FybFdXSjhwaDBYdUNrdkFa
            MGxaV2tIdTU1SVlwZnlzekxuZHFuOW8KWwPxvbEUP0PWovznulOrOMMvM8mx2cGA
            VfMIP48nqcQ6rffaKvzMEGRRwqEqcl+7Ke95y9hOlCITIlC2txf2CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-25T04:59:50Z"
    mac: ENC[AES256_GCM,data:MfIpKISPnKtsS3qoljyxwxzJAp7IdCxj6QQKl49tpsmFANgxrvxXQn40UrmCxjcuqW+bJCMX38kFtwcg6GdD8TpEmhM06z/Gy9kbCmVx+6a9yiC/W+TDVRKGMeDnIykKzVnK4WqnJHIsFALZbV6N1KvQYO1T3AYKw48lqRWND7o=,iv:57nhHPBvmt/3D833H7bdW15SEu17CQTesJckOAx3ZOI=,tag:xsG4vNs2o7WmJa6io8EvzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
