---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: 0.30.1
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  values:
    initContainers:
      - image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.1.0-beta-2@sha256:c63dc4e10d7ddb95c966194b5e6fbe2012feb7f932bafa24692daed3cf6c248a
        command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    config:
      pluginsDir: /build/plugins
    ingress:
      enabled: true
      hosts:
        - host: "headlamp.${SECRET_DOMAIN}"
          paths:
            - path: /
              type: Prefix
    
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp