# ref: https://headlamp.dev/docs/latest/installation/#create-a-service-account-token
# ref: https://github.com/joryirving/home-ops/blob/a03951cba04577b8329a9b14879c3649f74867a9/kubernetes/apps/base/flux-system/headlamp/rbac.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin
  namespace: headlamp
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: &name headlamp-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: *name
    namespace: headlamp
---
apiVersion: v1
kind: Secret
metadata:
  name: &name headlamp-admin
  namespace: headlamp
  annotations:
    kubernetes.io/service-account.name: *name
type: kubernetes.io/service-account-token