---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app memini
spec:
  interval: 1h
  path: ./kubernetes/apps/ai/memini/app
  components:
    - ../../../../components/kopiur
    - ../../../../components/litellm-key
  dependsOn:
    - name: external-secrets-config
      namespace: external-secrets
    - name: kopiur-repository
      namespace: kopiur-system
    - name: llmkube-models
    - name: litellm
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CAPACITY: 5Gi
      KOPIUR_UID: "65532"
      KOPIUR_GID: "65532"
      LITELLM_KEY_MODELS: '"llmkube/Qwen/Qwen3-Embedding-0.6B", "llmkube/Qwen/Qwen3-Reranker-0.6B"'
    substituteFrom:
      - name: cluster-global-config
        kind: ConfigMap
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: false
