---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app memini
spec:
  interval: 1h
  path: ./kubernetes/apps/ai/memini/app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: volsync
      namespace: volsync-system
    - name: llmkube-models
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_UID: "65532"
      VOLSYNC_GID: "65532"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: false
