apiVersion: v1
kind: Secret
metadata:
    name: backblaze-api
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JE8I+TcIn6+3S0IK3CD+7EpTKo7spAPbFg==,iv:ByWxBGiwae7u62ilqMSh++ocysn8pajn8w6PbxAdGPc=,tag:yRujSxlHTVYqU9CP8BYgtA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TcxN0Pslf+5UEWltIOl6061URnYBsR1Ci2EJzWSZ0g==,iv:BvhNn2kI8HFM+yHPpJ8qZiHnMxB4QxMA8AEBNAQye88=,tag:JdO0glaw7femhmHr+YCvCw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:KcGoPJUs3fcNChSKEqnDySD0Ys28MufLhMf3wNzabTwFoxBNR1c=,iv:JdErK8dTFn67T+AWrs3rhiepJk1lCh6dWxfvXHl85iU=,tag:9D5jaHRzoMC8eQeLZ14vpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcDhjY2FkalJPQmkwMStG
            UjA3eUlWV3FwZHhtaWFjQ21MMFZLcHhNczNBClNVZGMyaDFiMFhIczM3OVdhVDZU
            aDNjU3QrL05BWE4xRXNHQS93SlJhVEkKLS0tIFIvOG8vaExJQ0tsVmpnQStuemVj
            QUZER254ZWovZlVJanFjMTJKUUd4elEKN6Ti5UQoAizCvmGV6q66f0tEe0/PyaLS
            VwOlEVew3cjjwVdf+52H008UULj+brOV61QPB6Mc7iFC97efcHEgUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T04:35:50Z"
    mac: ENC[AES256_GCM,data:K4UJMm2kvSqF+daw+dLrKZgO+S8o3b5Q1EZ1bSKm2S64OdM8h9+Zt2NQGEE7YOA/rp5lvMQAKdm5PMdT4tJ5vu/EAJ3xV3BRBigrz2LruV/mGroe0mnUwcevEIqFOubVmTIio1ovZm9yF6q2bcWyw6IxXl7UEmYdXbw65V/E4TY=,iv:U07FEC7lP2sIfH22Yd9ZDIEE+BoASevnTbvJWTxUv/c=,tag:8Q1YXw8k93FfVHRG9h+A3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.1
