---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: paperless-postgres
    - name: paperless-valkey
  values:
    controllers:
      app:
        type: deployment
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.14.7@sha256:2a6d9f6461ad7e8335f5b2123a173b9e6002fda209af8a66483b0c00629569ab
            env:
              PAPERLESS_URL: https://paperless.${SECRET_DOMAIN}
              PAPERLESS_REDIS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-valkey-secret
                    key: valkeyUrl
              PAPERLESS_DBENGINE: postgres
              PAPERLESS_DBHOST: paperless-postgres-postgresql
              PAPERLESS_DBPORT: 5432
              PAPERLESS_DBNAME: paperless
              PAPERLESS_DBUSER: paperless
              PAPERLESS_DBPASS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-postgres-secret
                    key: password
              PAPERLESS_TIKA_ENABLED: true
              PAPERLESS_TIKA_ENDPOINT: http://tika:9998
              PAPERLESS_GOTENBERG_ENDPOINT: http://gotenburg:3000
              PAPERLESS_CONSUMPTION_DIR: /paperless/consume
              PAPERLESS_DATA_DIR: /paperless/data
              PAPERLESS_MEDIA_ROOT: /paperless/media
              PAPERLESS_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: secretKey
            probes:
              liveness:
                enabled: true
                type: HTTP
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
                type: HTTP
            resources:
              limits:
                memory: 1.2Gi
              requests:
                cpu: 40m
                memory: 1.2Gi
      gotenburg:
        containers:
          gotenburg:
            image:
              repository: gotenberg/gotenberg
              tag: 8.16.0@sha256:deac6b4a34d8c2e09f2fe15aff501dc4d6375bf0d4174c142cd01ee42ffe2e73
            command:
              - "gotenberg"
              - "--chromium-disable-javascript=true"
              - "--chromium-allow-list=file:///tmp/.*"
            resources:
              limits:
                cpu: 1000m
                memory: 1Gi
              requests:
                cpu: 200m
                memory: 256Mi
            securityContext:
              # https://gotenberg.dev/docs/getting-started/installation#kubernetes
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: false
              privileged: false
              runAsUser: 1001

      tika:
        containers:
          tika:
            image:
              repository: ghcr.io/paperless-ngx/tika
              tag: 2.9.1-minimal@sha256:20db3df89eaeb1b271dd840888fe909b88b12f4b86ef641ec07a1d45d4c5168f
            resources:
              limits:
                memory: 220Mi
              requests:
                cpu: 10m
                memory: 220Mi
    service:
      app:
        controller: app
        ports:
          http:
            port: 8000
      gotenburg:
        controller: gotenburg
        ports:
          http:
            port: 3000
      tika:
        controller: tika
        ports:
          http:
            port: 9998
    ingress:
      app:
        className: internal
        hosts:
          - host: paperless.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
