---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        PAPERLESS_SECRET_KEY: '{{ index . "PAPERLESS_SECRET_KEY" }}'
        PAPERLESS_ADMIN_USER: '{{ index . "PAPERLESS_ADMIN_USER" }}'
        PAPERLESS_ADMIN_PASSWORD: '{{ index . "PAPERLESS_ADMIN_PASSWORD" }}'
  dataFrom:
    - extract:
        key: k8s-documents-paperless-secret
