apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-postgres-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-postgres-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "database"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  data:
    - secretKey: username
      remoteRef:
        key: k8s-documents-paperless-postgres-secret/username
    - secretKey: password
      remoteRef:
        key: k8s-documents-paperless-postgres-secret/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: k8s-documents-paperless-secret/PAPERLESS_SECRET_KEY
    - secretKey: PAPERLESS_ADMIN_USER
      remoteRef:
        key: k8s-documents-paperless-secret/PAPERLESS_ADMIN_USER
    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: k8s-documents-paperless-secret/PAPERLESS_ADMIN_PASSWORD
