apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: paperless-users
spec:
  friendlyName: Paperless Users
  allowedOIDCClients:
    - name: paperless
  users:
    userRefs:
      - name: david
        namespace: security
