---
apiVersion: v1
kind: Namespace
metadata:
  name: ai
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    external-secrets.io/managed: "true"
    resource.kubernetes.io/admin-access: "true"
