---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./external-dns.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./metrics-server.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./bitnami.yaml
  - ./cnpg.yaml
  - ./democratic-csi.yaml
  - ./immich.yaml
  - ./backube.yaml
  - ./piraeus.yaml
  - ./rook.yaml
  - ./grafana.yaml
  - ./victoria.yaml
  - ./headlamp.yaml
  - ./node-feature-discovery.yaml
