apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: radarr-postgres-secret
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: database
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    username: ENC[AES256_GCM,data:t97e3Edz,iv:QTZgNYvf+hVH/innlu3PUpUOu5xmsDVC15/yiHMuVTc=,tag:BCWxJ1Dul+HviZFzF/VzxA==,type:str]
    password: ENC[AES256_GCM,data:JGrlcRS4/DCW8OzNtrvv32v6LEQ2V5CEBY9wBKEKjv0O/6kd/x25lWAbqohkth5irW2ssDmUZfEozEUvfQ6kNg==,iv:LlPqkMHUoG0uvgv/JZXiH3GGHSKtLCrgwNZphpD+UNY=,tag:WmDhBr2cAWxzyqA639iAFQ==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQVV2NnpBeGYxTUlnUmdE
            WEg5enFUaFlQUnFyekNYRWl2M0JIcnFEd0ZJCmIydmxXcnZwbFB0ZGRCTXdCWEdr
            SGhyMDdOOFdXZG5INTVoMEdMTDVyTVkKLS0tIEdzRWx5aFRtR0RpejFpdEJGYWVE
            U1hmeG1uWDVLeUY4TEQrdkRxa3MweHMKbgIbbsy3b4TLUlUG6ZJX6TG0HhVOijz0
            MNK0jf0uNSyGn7mXjpRISJtlZP6XB5hTsleIRWD6KxnwKJ3bJFSo5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T18:37:55Z"
    mac: ENC[AES256_GCM,data:0SvrF9Dw+44mNakjSIr1LhPk0cSJXblLxdN8Ty7YlrMP5Hm4w19JFEEXHlJGy5lOVcoXmg/mousxUWkF+XqntAQGp0hr9QtlaOB/SjA7OvCQGwDtgGKBxCu9eH/5ZY0CYy8hzMbWuDiufQrOBB12LQ37YSXd3kmpyWfpaFYe5H8=,iv:8LhT5EZEpLfg06ieT4gE4hzjnbiC6AiWic5ctXX3xEY=,tag:Zp1NwLsKjIRLK3BiognyOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:7Tq0tz/NVIeOFwZyxBP21soBEQSsMGrzD1opZ79C7MDNz48mlcmks7sNy5ZnVQ6q8BnI9wO1OHdIoO8EVvwZ,iv:+lnvzqT3MxmL9zikMSloDZ+I4WQzZmbIsRgXAg6DZPc=,tag:yUjjO0QQfHISeRcYdi8grw==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQVV2NnpBeGYxTUlnUmdE
            WEg5enFUaFlQUnFyekNYRWl2M0JIcnFEd0ZJCmIydmxXcnZwbFB0ZGRCTXdCWEdr
            SGhyMDdOOFdXZG5INTVoMEdMTDVyTVkKLS0tIEdzRWx5aFRtR0RpejFpdEJGYWVE
            U1hmeG1uWDVLeUY4TEQrdkRxa3MweHMKbgIbbsy3b4TLUlUG6ZJX6TG0HhVOijz0
            MNK0jf0uNSyGn7mXjpRISJtlZP6XB5hTsleIRWD6KxnwKJ3bJFSo5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T18:37:55Z"
    mac: ENC[AES256_GCM,data:0SvrF9Dw+44mNakjSIr1LhPk0cSJXblLxdN8Ty7YlrMP5Hm4w19JFEEXHlJGy5lOVcoXmg/mousxUWkF+XqntAQGp0hr9QtlaOB/SjA7OvCQGwDtgGKBxCu9eH/5ZY0CYy8hzMbWuDiufQrOBB12LQ37YSXd3kmpyWfpaFYe5H8=,iv:8LhT5EZEpLfg06ieT4gE4hzjnbiC6AiWic5ctXX3xEY=,tag:Zp1NwLsKjIRLK3BiognyOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
