---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-valkey
spec:
  interval: 30m
  chart:
    spec:
      chart: valkey
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    architecture: standalone
    auth:
      existingSecret: paperless-valkey-secret
      existingSecretPasswordKey: valkeyPassword
    primary:
      persistence:
        enabled: true