---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kaniop
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRules:
        enabled: true
      dashboards:
        enabled: true
    webhook:
      enabled: true
      certManager:
        enabled: true
      patch:
        enabled: false
