apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-repository-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopiur-repository-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: k8s-kopiur-system-kopiur-repository-secret/KOPIA_PASSWORD
    - secretKey: B2_KEY_ID
      remoteRef:
        key: k8s-kopiur-system-kopiur-repository-secret/B2_KEY_ID
    - secretKey: B2_KEY
      remoteRef:
        key: k8s-kopiur-system-kopiur-repository-secret/B2_KEY
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: k8s-kopiur-system-kopiur-repository-secret/AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: k8s-kopiur-system-kopiur-repository-secret/AWS_SECRET_ACCESS_KEY
