apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-repository-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopiur-repository-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        KOPIA_PASSWORD: '{{ index . "KOPIA_PASSWORD" }}'
        B2_KEY_ID: '{{ index . "B2_KEY_ID" }}'
        B2_KEY: '{{ index . "B2_KEY" }}'
        AWS_ACCESS_KEY_ID: '{{ index . "AWS_ACCESS_KEY_ID" }}'
        AWS_SECRET_ACCESS_KEY: '{{ index . "AWS_SECRET_ACCESS_KEY" }}'
  dataFrom:
    - extract:
        key: k8s-kopiur-system-kopiur-repository-secret
