apiVersion: v1
kind: Secret
metadata:
  name: kopiur-repository-secret
stringData:
  #ENC[AES256_GCM,data:mNhie4tRMgz+vrG4FvdV9lSo9kn6E9SAvo79RScAiK+HAblUITGjPqogQqDChwP9NWEuzUrU+hGH8QH0zLbD,iv:KWHkVa5xPVs2Slh0gR2sC1At2rPZfR3+4L6BbqJryPE=,tag:Y/pp8f1NDqXCK+G4RzP1qA==,type:comment]
  #ENC[AES256_GCM,data:wFMfNv2jjpCBaBK/zjcgfP1saPOMHj6Uf776Wy/CJeXdUWjTv7dW9uszbhopONwdzRsMUZoELTUqicIWKKe2VV9cDQ==,iv:d8PUkgPstLqKt7dJYH+1cFm5QW3flqnt0LWqcPV6pzI=,tag:yd2Xh0C8W+pR/Wb1W3fYgQ==,type:comment]
  #ENC[AES256_GCM,data:f93GEu7aGKNwbN0Q,iv:U9kms5Q/doyZ1CxKUdiqiMlVtfrvmDNky+sox1y88do=,tag:/0ytx/sd8zI0I4wtHF0lrA==,type:comment]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:xCATQMNr5arhFTN/LXLVihk26cWgAf3DnhNNiAUSwYRfmQE51lA5tWVm,iv:3A3Z5qr45KLglwOZJreZxj5BIrgo/u8Nl6PuFTW4MDE=,tag:BCHJ9NwAkUt+UwbuIkb8nQ==,type:str]
  #ENC[AES256_GCM,data:aOzga2GDTCpUsOXPbQ0gGIiYVSH415++TjCWfvm3xF43EDrRiU63Yz5l9dI0DJQ2fgyQ5Q==,iv:4MlHOx5cRvhxxr67kKjOSXfdcrhKycx75ivrPYKTlp0=,tag:E4OR7jSdu6+5DILzT8nQlg==,type:comment]
  #ENC[AES256_GCM,data:90kUwVnAqmgAdQ4pqp1Xi7tXNzrZyKHHBs7dAHk12RgmxnMIRhH52O4CqqbXSeihPUIi7MwUiPuXcf+FuHIs850V8GQ=,iv:MO7ODgW77rGNDPrnVfDzshMRmviyhmYuaLSYz9Uua9Y=,tag:EL+nU1zYUhsB3R5yOs0SEQ==,type:comment]
  #ENC[AES256_GCM,data:TsFPlnpwnt/94cQtrW4h,iv:K5HkaAryjppmMgjmPFoPRmAYmPytSWDFo+8/xwBcnjU=,tag:thjlKNUr9ay+PaAbnXuNPA==,type:comment]
  B2_KEY_ID: ENC[AES256_GCM,data:FzriY74LYuWevP0TH74//1a+WYK/UxBUjw==,iv:P+f8dSLomN2a7hw9UyuUzfvDPDlNFQwTeP/5oPIQlns=,tag:sZYlX3Kdd6IXSovTpKX0mg==,type:str]
  B2_KEY: ENC[AES256_GCM,data:92OYaH6yg+K7+JqMsrTTQKl5Gb5eJ2XVXG1ya+0v7A==,iv:qJMcLdM99FCRe+pb3UGXRuqKvaTNJ+pcAgbbD1FvBnU=,tag:hR9EvuzSa/dJpRknQoCI9w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV2FhTVNmWGxRc0sveTQ4
        akJZLzN2VE04OXgxbjNNb0FZYVkxZXJ4SkUwCnhBdStxb3pSamd1REc2d1BkaXlB
        NjNLTEt4V2JDOUlsQm1yT291RGdBMjgKLS0tIHlOSDgxZGZNbFZPMlE4N0pYYjhs
        ZDB3VHJOTHZaaitnTGRBYnhuc3ZxcncKHSC/knYP6O8RGBPrF83n4hdvHu5sBZE2
        OH9CbVADtC0jJzfAtCcKDvLFhnF4rbXR/7GiF80pr7qEZeSbJCcOSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-12T19:44:51Z"
  mac: ENC[AES256_GCM,data:HWsbL+aZQHKjdKFgGmZnaoXUI+XG9hNpgOqbyXne1w+cQSJoq96h9l7HUwlt8khX5knJNjOgU5OhT5kqeQyHsqr/m2NVrwOILPD67B+wwG3CXfn4RmL6icIU5J15WpoPSP4tta78BeCs06LWb+k7O1VDR2cpjpxlrbjstU7eNcA=,iv:qb4ssHPR/Iy5uZYTBLTP2s2hXjhrVMheneK9O6gS9nk=,tag:Az9SFZAxma8OUYQFAYjcqA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
