apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repository-secret
stringData:
    #ENC[AES256_GCM,data:mNhie4tRMgz+vrG4FvdV9lSo9kn6E9SAvo79RScAiK+HAblUITGjPqogQqDChwP9NWEuzUrU+hGH8QH0zLbD,iv:KWHkVa5xPVs2Slh0gR2sC1At2rPZfR3+4L6BbqJryPE=,tag:Y/pp8f1NDqXCK+G4RzP1qA==,type:comment]
    #ENC[AES256_GCM,data:wFMfNv2jjpCBaBK/zjcgfP1saPOMHj6Uf776Wy/CJeXdUWjTv7dW9uszbhopONwdzRsMUZoELTUqicIWKKe2VV9cDQ==,iv:d8PUkgPstLqKt7dJYH+1cFm5QW3flqnt0LWqcPV6pzI=,tag:yd2Xh0C8W+pR/Wb1W3fYgQ==,type:comment]
    #ENC[AES256_GCM,data:f93GEu7aGKNwbN0Q,iv:U9kms5Q/doyZ1CxKUdiqiMlVtfrvmDNky+sox1y88do=,tag:/0ytx/sd8zI0I4wtHF0lrA==,type:comment]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:xCATQMNr5arhFTN/LXLVihk26cWgAf3DnhNNiAUSwYRfmQE51lA5tWVm,iv:3A3Z5qr45KLglwOZJreZxj5BIrgo/u8Nl6PuFTW4MDE=,tag:BCHJ9NwAkUt+UwbuIkb8nQ==,type:str]
    #ENC[AES256_GCM,data:aOzga2GDTCpUsOXPbQ0gGIiYVSH415++TjCWfvm3xF43EDrRiU63Yz5l9dI0DJQ2fgyQ5Q==,iv:4MlHOx5cRvhxxr67kKjOSXfdcrhKycx75ivrPYKTlp0=,tag:E4OR7jSdu6+5DILzT8nQlg==,type:comment]
    #ENC[AES256_GCM,data:90kUwVnAqmgAdQ4pqp1Xi7tXNzrZyKHHBs7dAHk12RgmxnMIRhH52O4CqqbXSeihPUIi7MwUiPuXcf+FuHIs850V8GQ=,iv:MO7ODgW77rGNDPrnVfDzshMRmviyhmYuaLSYz9Uua9Y=,tag:EL+nU1zYUhsB3R5yOs0SEQ==,type:comment]
    #ENC[AES256_GCM,data:TsFPlnpwnt/94cQtrW4h,iv:K5HkaAryjppmMgjmPFoPRmAYmPytSWDFo+8/xwBcnjU=,tag:thjlKNUr9ay+PaAbnXuNPA==,type:comment]
    B2_KEY_ID: ENC[AES256_GCM,data:7SM0RLB1JxaB64t8tmCAyFD59gUsBhTQJQ==,iv:T14O7cfmhda7R+6Z/Q4hlrJgAVeLG8G0rUyrsn/oK5c=,tag:/M+VARZsD8bw1mfRPVA4qQ==,type:str]
    B2_KEY: ENC[AES256_GCM,data:abjrl1CJeRoM9mYkdz5rOcC4j6zfwu5El90NPTWMJw==,iv:+KF2tKtl9QKoRtw/2Zbqk1jVyWWQ62BuWK5Mo30UiRc=,tag:Km53I649xzEdoD5uiVPXlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV2FhTVNmWGxRc0sveTQ4
            akJZLzN2VE04OXgxbjNNb0FZYVkxZXJ4SkUwCnhBdStxb3pSamd1REc2d1BkaXlB
            NjNLTEt4V2JDOUlsQm1yT291RGdBMjgKLS0tIHlOSDgxZGZNbFZPMlE4N0pYYjhs
            ZDB3VHJOTHZaaitnTGRBYnhuc3ZxcncKHSC/knYP6O8RGBPrF83n4hdvHu5sBZE2
            OH9CbVADtC0jJzfAtCcKDvLFhnF4rbXR/7GiF80pr7qEZeSbJCcOSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T17:29:54Z"
    mac: ENC[AES256_GCM,data:1kHlOY7t9fuErfPF9KvdkIxfs45Lyc9HtXTEP+sl36op2fElbl6w3V7Kdq6WRMO927/TpPkpndkGNOWWXq00W5+C2YIvk/eIrJbYAN3dzSojTkkph0fv7v6xtgXylMlZbFF3GnJf7+rtOcni1+NR4BeQm7jvZFI4Pf+xDQm1klI=,iv:+uTad9pALX6+i8XZ6u3n6almE4jdHreKFKEwbpYcS8g=,tag:xj/v4bHCeyYVhw8P0N+1AQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
