apiVersion: v1
kind: Secret
metadata:
  name: kopiur-repository
stringData:
  B2_KEY_ID: ENC[AES256_GCM,data:f7Bd9RWStPXpbQ==,iv:MXAaxUoknxfFhLURPKdXFTUYJ1fI6K00tee28ZX/nUs=,tag:fyCWgjixyWKh0DEYLQ5Mvg==,type:str]
  B2_KEY: ENC[AES256_GCM,data:WMjjX5PWxwFOzw==,iv:cKPxQHL/zoNrR7z0gNKDm9ntqNn7Eoyap28ZRnBARks=,tag:/DnhEqQtC+Pj3unn/G/VrQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:f9VOMPKZxyu4rg==,iv:60yJHl1sScKmT7HVj4Ift3BjebpwO4jfGMzxsM96Dzk=,tag:o3YGcOv/mma23VndpwbTlA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdzJxTFlTQStUK25PSld3
        aFNtSFpzK1J1VzRrOWtxemg4U3B0S3M3UkNnCnhZNXh4Tk9qWGZqVlJiSjFBWmdp
        OEdXMTRoRDdNZUpoWGtTb1lOTWpYT1UKLS0tIGdLY1NoODJNRkdZdjY2UDM2VXNo
        NEV4SFV2YXVWcjlieENMUFRzdW11bmMKkHbTxpx0TsoJ4+RKQkTcAKwAG15hbtkE
        XLYR1hf1nNsJZWq2Pm8JAEA2TtApD/Y0OcX/FnT5rC2wuUco1IVwpA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-02T18:12:37Z"
  mac: ENC[AES256_GCM,data:ggHM5DN8U6HL/A49y3VrEm6G1MDt+F8GAAeG9xiwWjYKPvFRuVZlKkseZkUA/F+n5Nx3FQf45hiUHvYUo9r1dVLbEnurmxpph8f48XiY2plgsVvBGwN6iOm2Carr/89+JMFI74iGctNuoYtfocYYaNZXufIK8hQbPSYwMvp8JUY=,iv:VvsYcD+Lllbesj+c4Z543zwRxS1W4Em/w0Xlszji3QM=,tag:9+F9md8lw20DNCx267EDfw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
