---
- name: Setup k3s
  hosts: k3s
  become: true

  tasks:
    - name: Ensure required packages are installed.
      tags:
        - packages
      ansible.builtin.apt:
        package:
          - nfs-common
          - open-iscsi
        state: present
    - name: Ensure K3S is installed.
      tags:
        - k3s
      ansible.builtin.import_role:
        name: xanmanning.k3s
      vars:
        k3s_state: installed
        k3s_release_version: stable
        k3s_become: true
        k3s_etcd_datastore: true
