apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bazarr-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        password: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: k8s-media-bazarr-secret
