apiVersion: v1
kind: Secret
metadata:
  name: bazarr-secret
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:K4mIyOlgPcVZUw==,iv:zvDFocfxr0XoIOeyOPJbh4kfcVRUA/67Apgq5lth6Is=,tag:ke1fyqkBjXCJVAUGsashbA==,type:str]
sops:
  age:
    - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U0RBVTBVQy9VaXI0Q0s0
        dmxkVUt2aTdJZVBsa3ltZ2w0UXlTZmkzbGdrCkE4UXRzQ3Y1Y0N6Z2ZGTWhjRjY2
        SmtWaTFwaTNaaFk5aHlRWmQ3Y3Q5SlUKLS0tIFJXMC9mWEFZTHh3aEczREdpc2VP
        Slp3dnJUTjBTY0xNMDJxUHNNMWlXTk0KPLWmyjYXFRSAHlRubRSDB8b2V1G62mzI
        jKTlA+O2g8ASENfDjO7trVFo83tgE5YouMvG5hpzuSOQL4paP5P7XA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-02T00:52:30Z"
  mac: ENC[AES256_GCM,data:yRmD6+rEOJVwevNd6pO1VHbpuDUq0hArLM6trEjUdEkkLShWHLA6/ZR12IrcIQxIGRsIdsEzMz8IQ2ihnWyS4CNh4DYoLpHlJtgLgGYhjSNY/IGKR5OiIdAjCNDi29Um/yMC5D8BEkedkYRMODQroYmcdmb8WSr4vb9pQ6oJSfw=,iv:HJrXqfJh7YK2+oWHZxuwjH9cTibTs4FMk4DA60o6lNE=,tag:HCkbpFQ5oh0Y85xlP3VUyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
