---
apiVersion: v1
kind: Namespace
metadata:
  name: maker
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    external-secrets.io/cluster-secrets: "true"
    resource.kubernetes.io/admin-access: "true"
