---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    external-secrets.io/managed: "true"
    pod-security.kubernetes.io/enforce: privileged
