# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &dbName paperless-postgres
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4@sha256:9d25659c5b879b48695af426065b0aa81d64ed0a07ac31daef00f2afebb03d08

  storage:
    size: 8Gi
    storageClass: local-hostpath

  bootstrap:
    # initdb:
    #   database: paperless
    #   owner: paperless

    # note to self:
    # When restoring, the backup config cannot have a serverName that targets a directory
    # that already exists in S3. Will complain about "expecting empty archive".
    recovery:
      source: *dbName
      database: paperless
      owner: paperless

  backup:
    barmanObjectStore: &barman
      destinationPath: "s3://potatobread-homelab-backup/cnpg/paperless"
      endpointURL: https://s3.us-west-000.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-paperless-backup
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-paperless-backup
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: bzip2
        maxParallel: 8
      data:
        compression: bzip2

  externalClusters:
    - name: *dbName
      barmanObjectStore:
        <<: *barman
        # serverName: paperless-postgres-old
