apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: idm-admins
spec:
  kanidmRef:
    name: ENC[AES256_GCM,data:5ZPZN0pH,iv:96MWhXh1ZtA6izPs8Q4iAHp5zW5ITxeXbbWgeVsAR94=,tag:OP5tXRYOh1J2D4liHudkLg==,type:str]
  kanidmName: ENC[AES256_GCM,data:SUhaub74gCgYNQ==,iv:xwD8X1wTIUan6JxzjZ8QbVI6d5Jjt6cxPpM2u5B6jKM=,tag:heHINpabTDnJbT0DeJ+fqw==,type:str]
  entryManagedBy: ENC[AES256_GCM,data:04qc+54=,iv:7q5CGq2ZcsApeq0qihSUmMXTyyc72iLJqjg7UjZfQK0=,tag:Vi9JsXnJ6AfsfeeXbOFgKA==,type:str]
  members:
    - ENC[AES256_GCM,data:L2rzxhM=,iv:giZ7e5xRqsRDc1E+PC2v2suZP8+lD10SYIZYevYBkfA=,tag:d4c9kOE2BpppoKgqieLcIg==,type:str]
sops:
  age:
    - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNGFnUGtRWEk3TDMwSXJ4
        SDhqK0piM1J0cDRQN1ZsWjhSVkZncjNkR0JJClkwb3VoNFZDeENnZ0lUb3Qwc1FE
        L0hKNHNEQmRpSUI5WnNYYjJBTVpRVG8KLS0tIEZCQWswdUJwYjFZbHQ4ZEF3dVpy
        TG5uNExhREU2UWlLNWF5R3c2aXNNTTgKq3k5hyBZWU46UyXNIkBP6zw6RDp6ZkOo
        Q6LVmky/rqbzedmt5hBX5vD2lYIR3oOoPKiJBddqyu40MEHfZu8MDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T21:49:08Z"
  mac: ENC[AES256_GCM,data:KLUD23Rd0RuwwybMzz3+MaUBrOT4w6ykYeKvBCfMxN3PjAk2cPqnLs2LdJMXByZ0HDJ+Po4Sn5f5gzMv8JwOs9Z597hLVlzDYIHeqXgFuQRbPJ6RBaIHyGBrL11x47WAzZsBwDTU0hgUI5AqkOWA0QfzgwZ9AEu0LiwcTYf5Yz4=,iv:JZId0nZfyk7ux/wfUBLNv7Hi7b/Z0s6TsWzV2owrKQs=,tag:svd2ozvHrj0YIdhBRVHGkQ==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.12.1
