apiVersion: kaniop.rs/v1beta1
kind: Kanidm
metadata:
  name: kanidm
spec:
  domain: idm.${SECRET_DOMAIN}
  tlsSecretName: kanidm-tls

  image: mirror.gcr.io/kanidm/server:1.9.2@sha256:b2600b42dd4a91bcea66eb067b74a180b9ffaff322c3785ea0b411d12c51c7b2

  replicaGroups:
    - name: default
      replicas: 1
      role: write_replica

  oauth2ClientNamespaceSelector: {}
  groupNamespaceSelector: {}
  personNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: security
  serviceAccountNamespaceSelector: {}

  storage:
    volumeClaimTemplate:
      spec:
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: 100Mi
        storageClassName: openebs-zfspv
