apiVersion: kaniop.rs/v1beta1
kind: KanidmPersonAccount
metadata:
  name: dsluo
spec:
  kanidmRef:
    name: kanidm
  personAttributes:
    displayname: David Luo
    mail:
      - davidl2381@gmail.com
      - me@dsluo.dev
