---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: mcp-searxng
spec:
  image: docker.io/isokoliuk/mcp-searxng:1.16.0@sha256:d892b5aede28ab6476ba7ab3ce6b7e2e564ee43888e9c39ac5df52b74e1ca74d
  transport: streamable-http
  proxyPort: 8080
  env:
    - name: TZ
      value: America/Detroit
    - name: SEARXNG_URL
      value: http://searxng.ai.svc.cluster.local:8080
    - name: MCP_HTTP_PORT
      value: "8080"
    - name: MCP_HTTP_HOST
      value: "0.0.0.0"
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
