---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: mcp-searxng
spec:
  image: docker.io/isokoliuk/mcp-searxng:1.2.1@sha256:a86ee2d65b53750fb6379489e95ebe617db6a01da02ae23874075e8a44892af1
  transport: streamable-http
  proxyPort: 8080
  env:
    - name: TZ
      value: America/Detroit
    - name: SEARXNG_URL
      value: http://searxng.ai.svc.cluster.local:8080
    - name: MCP_HTTP_PORT
      value: "8080"
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
