apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bifrost-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bifrost-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: BIFROST_ENCRYPTION_KEY
      remoteRef:
        key: k8s-ai-bifrost-secret/BIFROST_ENCRYPTION_KEY
    - secretKey: BIFROST_SETUP_TOKEN
      remoteRef:
        key: k8s-ai-bifrost-secret/BIFROST_SETUP_TOKEN
    - secretKey: BIFROST_ADMIN_USERNAME
      remoteRef:
        key: k8s-ai-bifrost-secret/BIFROST_ADMIN_USERNAME
    - secretKey: BIFROST_ADMIN_PASSWORD
      remoteRef:
        key: k8s-ai-bifrost-secret/BIFROST_ADMIN_PASSWORD
