apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bifrost-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bifrost-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        BIFROST_ENCRYPTION_KEY: '{{ index . "BIFROST_ENCRYPTION_KEY" }}'
        BIFROST_SETUP_TOKEN: '{{ index . "BIFROST_SETUP_TOKEN" }}'
        BIFROST_ADMIN_USERNAME: '{{ index . "BIFROST_ADMIN_USERNAME" }}'
        BIFROST_ADMIN_PASSWORD: '{{ index . "BIFROST_ADMIN_PASSWORD" }}'
  dataFrom:
    - extract:
        key: k8s-ai-bifrost-secret
