apiVersion: v1
kind: Secret
metadata:
    name: bifrost-secret
type: Opaque
stringData:
    BIFROST_ENCRYPTION_KEY: ENC[AES256_GCM,data:kCUKIjEux4JcQ4Cv46XLUGJyItEx7X7hTct9VHP0OSG6giwfJwfI3TuRB+zKw78IHVVzqecv8NC7zqxi1GG8qw==,iv:GbzGw6s7AteQZRmT0ZQ2eC03mCRedjtbkNjgNFlE7yA=,tag:Od/cUq4EfJYurBOmDHzRcg==,type:str]
    BIFROST_SETUP_TOKEN: ENC[AES256_GCM,data:72q2MtxQWVMIxmNVKrXDThgzFb3pdHGO87qoqvsipYuC27mSYMmSCj+GFSE+yxmvjGNHE+CIhp7SU+YkRkK4OA==,iv:lClgH4j8hH6KqwyGr+YrMmCk7OHMIJdGbPTCDMQiK44=,tag:omaOUaXvxtXedYieDjzCMg==,type:str]
    BIFROST_ADMIN_USERNAME: ENC[AES256_GCM,data:WXDS/6A=,iv:CXBxTQ6PutXEbYjN3p4+/fFffBhJYnEqPNNHmAFpd5E=,tag:QD7kydjgPbFQ0dJup52ZWg==,type:str]
    BIFROST_ADMIN_PASSWORD: ENC[AES256_GCM,data:zBLkDbWNE4uw1xJGWZn78tHJvsSNFPMQNHF97Guz0c/GcKyIQFEdezKPI1/LRZtIXUNf2Gpr7LI8Lp0U/x1g/g==,iv:199YmMa7bVwANxIYOp+GJp22yNknnqcFre15d9WPaLE=,tag:TRqsWNwmtLEMH4aXJkiK1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNXRxa2RQSVd5Szc0SE9U
            a0xmUnY0ZTJ1eFFGVkJVOTQrb3RTeFB6RXhZCjZvV2VNOUwxUHcxTlo5SVJLS0Nu
            Nml5TFl4bU5MVktSanJNa1Fyb2RjRHMKLS0tIHVlcUxmNVlZT2dWcnJsV01Bc0Jw
            eXYyQlhZNnVwMHFiNzJ6OWhPMDJVS1kKoGmAogSFTRm2i4iYJKhVeLmF5baP0neL
            BdxuwDv90jPMY3JnHjVfz1Bzar/9TJ57Xcc+s7cj7i65+Im8lY9eeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T02:06:37Z"
    mac: ENC[AES256_GCM,data:Pn52KruMjJsRmCGuTbAFNfnBDAbIRubaPdxv0htvqdVtSrAsV0gXyeUe1HolfQfc0y/mnGWw4kIZ3mtqB5CDJc/tOgxvdt8bcqMzcbsiF0ablkVd+RNq7zwhJ6HkEtKLTzFBRBLwmaaV3qOeN2aeFG5L0v1OflmEUkKYFYq2/+4=,iv:IXdSr7wpg+1Ow1r/PpwWrpl72/YYxv0xY7bgWoEGCsg=,tag:im2kANW04SbaQkDq0E6ZFQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
