apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: searxng-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: SEARXNG_SECRET
      remoteRef:
        key: k8s-ai-searxng-secret/SEARXNG_SECRET
