apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:HYT0Np+b52tlmi6lG21N716mvB2qDnFlEDIl4i/LFkhWTWrlMipQYulayCJelBB6u/CJVmuPoy5TJnFJB1pJ8Q==,iv:fjCN2EAAB6vRhj7WQmmOQKBkyD/htqXQF4DBP7sijyQ=,tag:SeoAOFWZyTx6DiDRub5PXQ==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuLy8rd25JRUxPOE1URGdl
            Zmg2TDhiamRYQ3VDWXZLTDlYUUt2VEZGeGlNCmEvWFVYUFNSdVV3L05uc2VrTllD
            WDNpQVk4OU1NTndlUGQzT3NYZWFPZ3cKLS0tIG5GQitLdFo1V2VTYXN3QUFwZzNU
            S2NkaTRHOHJGNUZTczZUK2ljVGJKMkEKYJQG1b0RQqm0uz0Ua+zIFeWbHxjvm8Vq
            eH1mEqmHWfbvIq661nriNYT00A09M4HHlnur7Nbj9cVvD+SsJDADtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T22:46:35Z"
    mac: ENC[AES256_GCM,data:4KwVQJdzStcToPM4MljemPrteKNHaWQrEflLXxp1ZvsnJTrbMAL5KqGIB82H/WIgH4Bql1PXYAL5gFs0u9PW4hzRTtQO2ekVzUzi7JmT2UrB9x6pBtkWEZHb3BYQN/Z9xIMwlM2Tuzjoo5qts8YbalzUR45Dy9R4UYfmytX9bHA=,iv:I/Bll7BLGWKJn1M6TG3OFwYF/8w+16p1K2gFbBhlOCk=,tag:6Kog4j/tPvwv2d/FUt4HNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
