---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: hubble-users
spec:
  friendlyName: Hubble Users
  allowedOIDCClients:
    - name: hubble
  users:
    userRefs:
      - name: david
        namespace: security
