apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
type: Opaque
stringData:
    target: ENC[AES256_GCM,data:Aw70waG8KgpXkVTNGoQ80qQcwLlTEx970SQpzSeImmLCQ4aXk0BqAbh6tdePFJMJ2+R8jrQ=,iv:Rb9yD8wFStyKh8xwIh4K/3g2MQO5KTLQkEn+p+jBHds=,tag:hGJ4WOVi2pZPK260+XxKtA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:52S6E2sB17L+zdV3fy5C00EzYTPXHIL9G5VatJ1w,iv:BUDslyDZTUBXIPgMzBfizZMqAO4dHeKitU5Jfye1BdI=,tag:fJYAInCAJzeGjdHhvjMWkA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fKOmBCAB4rOfvWjW3aGsPt4W/GHWGLFatQ==,iv:raaPHllhO6DmMX4NK+ewjXnwVKnlW87dCIzRrRumnTE=,tag:3sr1ayVpbkkr061yxVz8cQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:K5CIHvCYTjb9Fx49oB23u4Acp1QUTLVEZkDfGXLNFg==,iv:8GrLl+w6apVqrtC8+si5v7RaDNx+EBtKPFqVD+WVC9A=,tag:LKv7GVWcAFZskE9DnrBC+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hkggfdsuse44s5aw3wulvq45h9u93lgvgarm8leqxnesf6knyffsgnh78f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQM2pYZ2drVFM5MUxrdFIr
            bktUNWlDcDgrNGh6b21PME1ZNkM1T0lnL1VZCmFPWEpiODNSU1U1T2M1UmM4OFYv
            QW0wSzlyaTVKQnM5eHpZdUUwTk9MK2MKLS0tIFRTY2JXcjhKTUdHWkxUY2o0YlBK
            L3VCZ2FnR05QeGR0U2xKVFErMGgwM28KrwS4OhvXdeH9+blhFqrzf2L8vQSgA0d+
            DHNRi7ehPaiOQlmaeRFflTZ2DWWyBqI55v+89yXgSk1HQOFHZOrgPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-16T11:54:28Z"
    mac: ENC[AES256_GCM,data:Bf2o9chWaXWi+ij8l1h4J/RChKCznG6+Qf2yLF0CrqgR6XYM92ca0PtUuiLpFZfiPgKOG/3XM1lamJEOJwpcROqi+558VjhD48IxRYCgbkGWG4wBtVjsVC+0S/J6O0Fb38rnL0HOB4gHPqo9A4eLr5MRA3zrWRuyJAnBJnYYtms=,iv:dXc2WUidb2yrw9ApqzcCgFPmJOVogUuRhV8R/RBdE1k=,tag:b5kNb7XfLwnG+lu3RCflfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
