apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
type: Opaque
stringData:
    target: ENC[AES256_GCM,data:67QsCiy+5Eb134+dSLSyE2vW3TrlwWeDEhxTIs1qvNqE85YZyyRHEyk=,iv:mlWfsIBuRAxHmxgYZqkjnhcNJ9FfYeFUMmO7sBTx9tA=,tag:15rUjlY/PvJa+t37af9yZQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:OXx5h+521iBzLSR8vrGEnMPfKs61WK1G7dURUrc2,iv:cSsFXMTCbkrVYJdRzQgFR2vtGF/E16ceWcvPfOIhbek=,tag:DFYchPSdJSIOPnuZ98m0Xg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fKOmBCAB4rOfvWjW3aGsPt4W/GHWGLFatQ==,iv:raaPHllhO6DmMX4NK+ewjXnwVKnlW87dCIzRrRumnTE=,tag:3sr1ayVpbkkr061yxVz8cQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:K5CIHvCYTjb9Fx49oB23u4Acp1QUTLVEZkDfGXLNFg==,iv:8GrLl+w6apVqrtC8+si5v7RaDNx+EBtKPFqVD+WVC9A=,tag:LKv7GVWcAFZskE9DnrBC+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hkggfdsuse44s5aw3wulvq45h9u93lgvgarm8leqxnesf6knyffsgnh78f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQM2pYZ2drVFM5MUxrdFIr
            bktUNWlDcDgrNGh6b21PME1ZNkM1T0lnL1VZCmFPWEpiODNSU1U1T2M1UmM4OFYv
            QW0wSzlyaTVKQnM5eHpZdUUwTk9MK2MKLS0tIFRTY2JXcjhKTUdHWkxUY2o0YlBK
            L3VCZ2FnR05QeGR0U2xKVFErMGgwM28KrwS4OhvXdeH9+blhFqrzf2L8vQSgA0d+
            DHNRi7ehPaiOQlmaeRFflTZ2DWWyBqI55v+89yXgSk1HQOFHZOrgPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-16T11:39:31Z"
    mac: ENC[AES256_GCM,data:C+GKRP8p/uafKa2kDrkUMswCpwK8D9xs2yrP0EpsOvDTfy2iydB3sS04xNMI/gJc3BthnbRQkI90VvsPliPYTvQA1WElLnUQvKIhr+TUWQ8WzlInkoz4gPK28koUjA67yL5FMo3DxLkZBINY7NXpR9+vTSMgKZa74OaxGrMyGHE=,iv:fHqlktRYFrxBL1muqKZXtpi/4TAAm2prTMPKq58JiJo=,tag:xuAJsmq0XnHi4H73rXPDlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
