---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  chartRef:
    kind: OCIRepository
    name: flux-operator
  interval: 1h
  values:
    serviceMonitor:
      create: true
    web:
      networkPolicy:
        create: false
      config:
        baseURL: "https://flux.${SECRET_DOMAIN}"
        authentication:
          type: OAuth2
          oauth2:
            provider: OIDC
            clientID: "${OIDC_CLIENT_ID}"
            clientSecret: "${OIDC_CLIENT_SECRET}"
            issuerURL: "${OIDC_ISSUER_URL}"
