version: "3"

tasks:
  network:
    cmds:
      - ansible-playbook playbooks/network.yaml -K
  install:
    cmds:
      - ansible-playbook playbooks/k3s-install.yaml -K
  nuke:
    cmds:
      - ansible-playbook playbooks/k3s-nuke.yaml -K
