---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llmkube-hf-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: llmkube-hf-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        HF_TOKEN: '{{ index . "HF_TOKEN" }}'
  dataFrom:
    - extract:
        key: hugging_face_api
