---
apiVersion: v1
kind: Namespace
metadata:
  name: social
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    external-secrets.io/managed: "true"
    external-secrets.io/cluster-secrets: "true"
