apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
type: Opaque
stringData:
    homelab.agekey: ENC[AES256_GCM,data:1nMuru0CrYtZvVKvXQD/iOSrtga3l6JAp3bQCLvjL2XlT8ubI60krElFKUMFG7E9kYOLgqdhxCTiRKFXofV0mNYWi3Eq2RyP2d0=,iv:BbVVcIdPuC8EmXYt7irBUa8AEhE+XMw0zBAS91Lp3zY=,tag:8f7fYCa8QZnvjqHEWG7/6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y3liM1Y0L2c5WjJYbDJU
            Z1lhN08xVHBCRUkybElxWm5zaGZSc25pZ2swClI5dlVLUldiSUhkTXZhVTNqTlNU
            MnE1VXpyS0tvTFhHWUZud1h0Yi8wRkUKLS0tIGZnSEpOODAyOEJqRlZnalE5K3o3
            THJidVNDWHVKckY0TElxVXZ6SWxIV1EKh7QfVxEHy9gJF+j2ZqYP8vOC2ROngvus
            rB2oahw+cZWXCAAQOH4pEdr5h4dVZAbDj0RnMdjWE8oZoPWUAppVbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-20T06:13:10Z"
    mac: ENC[AES256_GCM,data:oeDUXuox/Kar1RpFVS62dufUBirUPrVLxfJiny17SMqYcErz6SktAkCvyk53qZD3kCwhZuySvJ91Yd9T8mJJIRKSNyMe3nNczYlo4GrEN/NyBE/hxG41Fe83fZTX0rLFnMXGBWTRQLQumYA+xdBgsqJ93RpuZf/cY75N9/CrGPo=,iv:R6VyhSR+/GF8bcJaMe/cWxf2WCshay70jeaLbfh6GSs=,tag:P3iyoUG7zU7beRhZck4ieQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
