apiVersion: v1
kind: Secret
metadata:
    name: gotk-notify-secrets
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:vBPaGDUa+X9Az3vS1d6TDTbdCumtz26ls+wNHDyrPVvk7WZ06bm25lHpmw25St/KUcRgx41mmxnMqLtWqSn+Z0vbWfvLKOFQV6mVky6YF4r8GS49rRHfBVYNUybQPYrs4twsZ/xV7Quvk+kHGhD7jZwfcQX5+hgBmg==,iv:GdttfCG50KVgQ3wgfNJnnR/Weg1tEOP0RtL1cFCkTMU=,tag:Ywoz14M+PpH94ogaF7F8pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m0hh84hkt3nj4cpnd2sps8ffa4sm2dshwe7ryurj9v6nee06h4jsy7cj2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaWNQVitkT0p4emxrU1Yv
            eUN6bzNtQjQ4MElFR1d4Y09uQTJ0ZjB2Q2pJCm9qYi96c3l4cjZMRkhrVVZJYjJS
            VnpIR0pCcDN4MkI4ajAzOFFZZUVPU0UKLS0tIE1SRXdRbHBBWC9ldkZJVVBLdktw
            OExTaW9RMTBBbVN3TngzTFBncy9UNkUKrXh4ujtcrrKU8NGfilj13iq6l4eG8SlS
            16IZTu6CKybVjwwIdxcxX3hCyhW3hAOJrcVrBZYa0RCjLnJzBG62iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T09:47:43Z"
    mac: ENC[AES256_GCM,data:40DiNHpa1nEqhIwhO6EK7eV31iX3538J/8YK8aj7PyNLYy93cApfMeHPxEGdT2epCIxy8ZvgxuaIUBfTf4lf3Aw+zn4IsHm7EcTKgUy+c1pVp7L12Rq7YK+ierdacd29FDXutCrzwJ08WDuEhN2Vioi0PYBp1RlTq9u/zl2LUuc=,iv:IH4L11Ws/CKkz5Ji4VejS2/KLanQk6XCHfzQZsh70ao=,tag:GQniTRr9OxIGN7274R4JlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
