---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./daemonset.yaml
  - ./podmonitor.yaml
  - ./grafanadashboard.yaml

configMapGenerator:
  - name: intel-gpu-exporter-script
    files:
      - exporter.py
  - name: intel-gpu-exporter-dashboard
    files:
      - dashboards/intel-gpu.json
    options:
      disableNameSuffixHash: true
