---
- name: Set hostnames to node name
  hosts: k3s
  become: true

  tasks:
    - name: Set hostname to node name
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: debian
