apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: litellm-secret
    annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:nUHKvxUDx9dNe7ooc/6+RvBEr8YeuqBqXV+4r5N/KROZcKyRutuoiBGdNdgKibwDpzcs,iv:Mkp05aKaffnIJtq/LdP6ATEW6XpMjSlOOSrKFJhUs7M=,tag:mkAln5/2/xZVUTmCS13HIA==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:+2LJKryQEddhcI1MGEXigkW6Oq8nUt3PZtCf95zLep/8KMderK6mkUJhl6s7wqGkdtdk,iv:EdJcpus9yszJbypQTS7zlqlBwJDUN5fBCKcqlOtH9gw=,tag:vftok7G/Fn1qRiYVuwmM4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOelBSdjNEWXN4ZHNzTDI2
            MjZ4d25Tbk9tdWJiV2ZEQXlkU2djY0dvUDJ3ClRaUnZHaHIyM01NYVlhYVRyMmtx
            cDEvcHE3QzhHS0wxSFFnZzhZZEZvbnMKLS0tIFBWMnB2VXRKUW5yeHRRVXJBTUJ4
            WEFPckxMR216MjF0NFJGRjJJVGxpMXMK7oSn5EMhX1ZmNiQ9Dp38woBAp/mZwAKd
            WPOhfnsnd8MFo+XRwrTY5myl2tgoIn/nBaLzZQFKiB3gp+YA2bo6TQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T17:11:27Z"
    mac: ENC[AES256_GCM,data:5lvbpA7H6JJbIn6h5DhRtwloxRqwlCm91acYcGfmvrdY9DzjWhXacSTz+StXOfJZ5fFQtjxWD2GC/46Tj5g+7FzQepGYVPcgXx8Zge7LgydrLdI8wJcsdl0P+IL1RsrUipSrXEYWcKCDhG3VVyYhNY79Vrzb7ZiT7b5erFviEeY=,iv:ufZrCTiSdwFv24Q5gV7dBbAhcggwdEpgdKKpAC9Czn8=,tag:gJp8vop9rAvK1aN63ttRDw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
