apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secret
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Replace
      data:
        LITELLM_MASTER_KEY: '{{ index . "LITELLM_MASTER_KEY" }}'
        LITELLM_SALT_KEY: '{{ index . "LITELLM_SALT_KEY" }}'
  dataFrom:
    - extract:
        key: k8s-ai-litellm-secret
