apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: litellm-postgres-secret
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: database
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    username: ENC[AES256_GCM,data:o7dbHVJdMQ==,iv:Lk1hpF7XAwiGQEQNWiN/wrh3Iih15q0cvA0iYWRRCmw=,tag:/7xWUNTgcUdRHXcWIGsAMw==,type:str]
    password: ENC[AES256_GCM,data:20gIlEHLRI0bHVwlqCksPAaFsDNp/n4Z+QyU5O7oM2O4uoUXN36RiCarJ6bGhBhQc34mnteHlVhNnefdSg/fYA==,iv:Oz9HtoefPXb/G5f+BD8y8F5LT5xbaE779Y/2PewySCA=,tag:BLIND8VuMDzzuoTPZWTpsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4THRJYW40d05tL1pzVkRY
            SWpnMjJFcjBray9GQ2dWUjJoajhlRDVlaEZjClkyRnRVMlhwM3Eya1llMlQyaWxY
            NWNGODNTdHVkSjREeXh0NVRyNXJmR1EKLS0tIGVSV0s2Z2JrQk5FRnVML3pmdHNn
            cVZYcVJLN3lPRDY3dGdHdjRkMUdwTjgK+ytiLxXl5ldBg3trhd3NOXfn80RM2CVo
            gwyOY0QGfTRsCw1z3QvHNFPXWlsybONeNUoi+no3UNdyWaJBjYc0hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T17:10:46Z"
    mac: ENC[AES256_GCM,data:PTfvddMhWDOWIdZ6DW9vR2jrHEDJ1WIuW2PwXrTvSnP8v4gr5IwCNWnlz0WTqlxmHyPOwNagP9WQHJWEok4O0cJIROq68oZ/DcSMfolvH2HZEoJk7L0eX1HMq46L5+LtmxL5zNfLnGyw/sSQVrnfQcwjwIZddQV8aa0rWROjeAE=,iv:UCWI17UOTJYI4l6uBLqSAB0iM6J2+Ua3cdRNNeVZzao=,tag:kEr7EH7dHrRhj8QmDHhRxg==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
